---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: billing-app
  namespace: billing

spec:
  releaseName: billing-app
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system

  values:
    controllers:
      main:
        strategy: RollingUpdate
        containers:
          main:
            image:
              repository: getlago/front
              tag: v0.50.0-beta
              pullPolicy: IfNotPresent

            env:
              TZ: Australia/Sydney

            envFrom:
              - secretRef:
                name: billing-secrets

    service:
      main:
        ports:
          http:
            port: 80

    ingress:
      main:
        enabled: true
        className: traefik

        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production

        hosts:
          - host: &host "billing.node.net.au"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http

        tls:
          - hosts:
              - *host
            secretName: *host
