---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: billing-app
  namespace: billing

spec:
  releaseName: billing-app
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system

  values:
    defaultPodOptions:
      imagePullSecrets:
        - name: ghcr-secret
    controllers:
      main:
        strategy: RollingUpdate
        containers:
          main:
            image:
              repository: getlago/front
              tag: v0.50.0-beta
              pullPolicy: IfNotPresent

            env:
              TZ: Australia/Sydney

            envFrom:
              - secretRef:
                  name: billing-secrets

      api:
        strategy: RollingUpdate
        containers:
          main:
            image:
              repository: ghcr.io/the-it-dept/lago-api
              tag: v0.50.0-tid
              pullPolicy: IfNotPresent

            command: [ "./scripts/start.sh" ]

            env:
              TZ: Australia/Sydney

            envFrom:
              - secretRef:
                  name: billing-secrets

      clock:
        strategy: RollingUpdate
        containers:
          main:
            image:
              repository: ghcr.io/the-it-dept/lago-api
              tag: v0.50.0-tid
              pullPolicy: IfNotPresent

            command: [ "./scripts/start.clock.sh" ]

            env:
              TZ: Australia/Sydney

            envFrom:
              - secretRef:
                  name: billing-secrets

      event-worker:
        strategy: RollingUpdate
        containers:
          main:
            image:
              repository: ghcr.io/the-it-dept/lago-api
              tag: v0.50.0-tid
              pullPolicy: IfNotPresent

            command: [ "./scripts/start.events.worker.sh" ]

            env:
              TZ: Australia/Sydney

            envFrom:
              - secretRef:
                  name: billing-secrets

      worker:
        strategy: RollingUpdate
        containers:
          main:
            image:
              repository: ghcr.io/the-it-dept/lago-api
              tag: v0.50.0-tid
              pullPolicy: IfNotPresent

            command: [ "./scripts/start.worker.sh" ]

            env:
              TZ: Australia/Sydney

            envFrom:
              - secretRef:
                  name: billing-secrets

    service:
      main:
        ports:
          http:
            port: 80
      api:
        ports:
          http:
            port: 3000

    ingress:
      main:
        enabled: true
        className: traefik

        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production

        hosts:
          - host: &host "billing.node.net.au"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http

        tls:
          - hosts:
              - *host
            secretName: *host

      api:
        enabled: true
        className: traefik

        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production

        hosts:
          - host: &apiHost "api.billing.node.net.au"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http

        tls:
          - hosts:
              - *apiHost
            secretName: *apiHost

    persistence:
      storage:
        enabled: true
        type: persistentVolumeClaim
        size: 25Gi
        accessMode: ReadWriteMany
        retain: true
        advancedMounts:
          api:
            main:
              - path: /app/storage
                readOnly: false

          event-worker:
            main:
              - path: /app/storage
                readOnly: false

          worker:
            main:
              - path: /app/storage
                readOnly: false
