---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-portal-gotenberg
  namespace: flux-system
spec:
  interval: 1m
  dependsOn:
    - name: apps-portal-postgres
    - name: apps-portal-redis
  path: ./k8s/demo.node.net.au/apps/portal/gotenberg
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
