---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-portal-redis
  namespace: flux-system
spec:
  interval: 10m
  path: ./k8s/demo.node.net.au/apps/portal/redis
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
