---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ghcr.sops.yaml
  - secrets.sops.yaml

  - ks-portal-redis.yaml
  - ks-portal-postgres.yaml
  - ks-portal-gotenberg.yaml
  - ks-portal-mailhog.yaml
  - ks-portal-radius.yaml
  - ks-portal-app.yaml
