apiVersion: v1
kind: Secret
metadata:
    name: portal-secrets
    namespace: portal
stringData:
    APP_NAME: ENC[AES256_GCM,data:s5xsZU8NT/tUarWbBWi5,iv:YEqGzgXjlfYvcFbGvXOjBhzcLsKgjf/gN5oi1pMi9EE=,tag:OzFcD4zJ6tctuHklvmswiw==,type:str]
    APP_ENVIRONMENT: ENC[AES256_GCM,data:oFQiU7BaVuk1vQ==,iv:rbylTdyLgVn3KwK0lTFPV2GCvEYjiQJV7owH7mWJwLo=,tag:uoqPdSGUNA1rKBmo1OBASQ==,type:str]
    APP_KEY: ENC[AES256_GCM,data:i12age1HavK0+FT4/cmgmBefrYcQtwtN/sS2FqTLV4Fm74r1fmn3QX3nO8WEO/2Nr2eZ,iv:zlpgAdbBbpten0uWpqIp6bQYpSbzySDoGfELV4Rj7/c=,tag:u3jKDuXu0WMmcrgrlPO8iA==,type:str]
    APP_DEBUG: ENC[AES256_GCM,data:7oVdbYU=,iv:adGe8jIaop5/zkgsR32DRWceyWdYywS3AYRNVNWEGuI=,tag:3DPbUClbwAymD3jVhb/Brg==,type:str]
    APP_URL: ENC[AES256_GCM,data:d6VXYSF6/tIRLJC54pGhcdSdHegs6p5c,iv:k3HAt/X78hsRHIoiTDVTa4xMelkd0LQvKRh/fel8kJ8=,tag:EAHcJ12kTeS/D9l77de0Hw==,type:str]
    LOG_CHANNEL: ENC[AES256_GCM,data:X830CXhM,iv:nclwHy+Mg+VzdeS0ZZfF9EjOF3e8Pfds7oOOb1O4Bxw=,tag:0e1fVoamXMmyD4DL1THsLg==,type:str]
    LOG_LEVEL: ENC[AES256_GCM,data:OGu/WS8=,iv:i8C6vjpb0z8uyHYaTZKSAhFv6DqlAcKTNKWtvnBGTQ8=,tag:klEMyXA/L4cfZp/SCqkjTQ==,type:str]
    DB_CONNECTION: ENC[AES256_GCM,data:I2JVhSs=,iv:KQz1kaQlV8Kxp66KEC9IDRaF1yG1MtnNGrazs85xTJc=,tag:SNcbzIOqIcdgmGVLiHeP6w==,type:str]
    DB_HOST: ENC[AES256_GCM,data:iPx5IqhpfExORYwC0tjBTOmVsz4wgY5yLN4=,iv:0PRKEbsWIIKjN5QMp7HLvgUqRIoR/1tIq8ISDDEDtlY=,tag:hFnUq1YnaaSYeJ42o78gnA==,type:str]
    DB_PORT: ENC[AES256_GCM,data:e/sJgw==,iv:KzFm4nm9XXnWpBKnVTOwno8oMeXY3jjDsF8GM1jq1Hk=,tag:3XmSoEgdJZvAeksU88CkXg==,type:str]
    DB_DATABASE: ENC[AES256_GCM,data:PVRERCc+,iv:9mQtvHwCEn6Ywq3EHO3bAvKaUwnPOOD4OQ4MZkCa9gY=,tag:WvLjRondGBaSLIyorWBrzg==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:R6y6nRUA,iv:FjT/JRDvwxLHaWIfHB97fYXfsbyOqjvhCWC6vzidI3Q=,tag:k6R8IpGjENoQ1mWeApRS9Q==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:q0dydxp/bHRrUMP/sLtnCrv7lsSAMX0q4NZJDL4LDUNkzqj5tFY8VSIaYpvl7cDsqOSavsLre6o5uFpj2FLL9rNaX0NWLxozVNlycHGD9cI1Tiq0vi9H8VL2+YGwMg==,iv:75qpRPwoa9DB1wrVmxiirSIxeMJJAZgC3dRDhLLPaxc=,tag:Vh1XeRrDh7vCzSfe4uI9ew==,type:str]
    BROADCAST_DRIVER: ENC[AES256_GCM,data:gP7El+E=,iv:kYRf4MyyLNqtHnoBsrdSOAUVlwqeg5XTVPgBzDq5G+4=,tag:I5kvcGJkWBotOaUmR2OqKQ==,type:str]
    CACHE_DRIVER: ENC[AES256_GCM,data:slUHwzA=,iv:Ag6Nd/oZ02NloEtE95xzXuJEr/iaSWxMUE+3zr5mQOs=,tag:h59z7WVix6uiSCcZ7sP4Sg==,type:str]
    FILESYSTEM_DISK: ENC[AES256_GCM,data:XrgVTGM=,iv:1beagAbCsuFsBTK3ISmJW7rUD2sHMgM8l3Nyb8KL4MA=,tag:Phx0mP/EOKe3XXs22gw6ew==,type:str]
    QUEUE_CONNECTION: ENC[AES256_GCM,data:DjLLnQE=,iv:3ow7EbOps4d29k+2A901njigeax4FDd1HBZPipRt1/c=,tag:ZyF9XowGnVaF5SDVLgKnUA==,type:str]
    SESSION_DRIVER: ENC[AES256_GCM,data:OAdUZDY=,iv:qrspppiktLNDJCO7YG00iVvkPglmAoOlZb5pa9+ZbCM=,tag:JKGMj1CvIIiQu9d4ztRqag==,type:str]
    SESSION_LIFETIME: ENC[AES256_GCM,data:XjZ0,iv:KZ5WgdXNnWgWbWzV9j0ryg1GST6WAioWRY1PNEfHwU0=,tag:yrGCMqUPzSutHmxqw1zvzg==,type:str]
    REDIS_HOST: ENC[AES256_GCM,data:oWSc3GbpKrK8xbfEebRvYjWtrA==,iv:AJvotZ9lUY4g9BWvnV1d2Tzqs+vXOm2ghDvsRpt/VxY=,tag:oIETYcLKbyRvIMRgQxDBkg==,type:str]
    REDIS_PORT: ENC[AES256_GCM,data:nBiL4w==,iv:fAx2eP0lb6jYZFCABtZOyMQN2GIZxFtgZMvtFeOctUg=,tag:01A9hYSP7748VjXWe9lLXg==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:m51Pt/O7aEYazk0h7rniX1XrzdXewUPtMN3aFBK3pWF7pkS9wzYrufeLL6ibyYqhDhWRpDyGTVQI7/gug4IHNAGGn3Jlyfk57j+jO4vqz3zA9mw1QacFtvRitZ1Jgg==,iv:Navc7wSay9hAT7p7req/P2LLMPHBUV6Nanwaea+HK4Y=,tag:0oLGfNV3wJt/ttlqb2MoVw==,type:str]
    MAIL_MAILER: ENC[AES256_GCM,data:1q6MzA==,iv:foPmiLXOAM4bhjhp+NkGAgdbCagOUmagI1cX5nQXhWs=,tag:z5IvGHT/OVfVo/yoml0ZdA==,type:str]
    MAIL_HOST: ENC[AES256_GCM,data:5PwQkO4j2JvSBcTzZPzvnw==,iv:ERL3GFg+xAb/jJUGD1e2FmaKvzmXEADChu6zT5rnXb0=,tag:ioubue/f0HcaGpRBri4Dhw==,type:str]
    MAIL_PORT: ENC[AES256_GCM,data:tnucIA==,iv:lKMq5zUgsuQvXeBuMccBwcS4UU17HxdLPiJTUjvrV5c=,tag:C5YnnNkH4zGIc56iVjYKlQ==,type:str]
    MAIL_USERNAME: ENC[AES256_GCM,data:wfeVyA==,iv:qGscctpD4bPpsAiwzAai3lXM+TnjAjSPX4RoGeNoz0U=,tag:Bws919rrL1PJcxnX9D10AQ==,type:str]
    MAIL_PASSWORD: ENC[AES256_GCM,data:vzPRpw==,iv:2pkjy50SOi1z3knE7e5Q+wxq7mz7fxyx9I/f9XYBERk=,tag:7eXKkrLtwXFXiWDv0svV4g==,type:str]
    MAIL_ENCRYPTION: ENC[AES256_GCM,data:7eceZQ==,iv:3QbXO6VjuP33VYERd7/rq6RwcGk6/l2SYtPW87PK6Ts=,tag:mfmjQIng0lMoviQXoKxOWg==,type:str]
    MAIL_FROM_ADDRESS: ENC[AES256_GCM,data:0mJSjjjB2gMKauHDv5/SEQ==,iv:fyhCbXHfnLnZhfwFIHb9mgDpBKsD2ATNeT4cP4QJ1zc=,tag:ytd1EOkHQVeqc9f6u9TqWQ==,type:str]
    MAIL_FROM_NAME: ENC[AES256_GCM,data:Lli5LCkIe/oNfh+goLvd,iv:vatM1/nQ1miNSqQ2AtOTBzzNaR7h0A3jNFyBha172FQ=,tag:Y7daZzXgggmp81L7rZY8SA==,type:str]
    PUSHER_APP_ID: ENC[AES256_GCM,data:A70BUdoZpA==,iv:RFiGvpFg7qWMz1lPtp2Acz2QhPh1QmcN61tNEYOCnik=,tag:TWyYhtXQzPJB8vt5LG13ww==,type:str]
    PUSHER_APP_KEY: ENC[AES256_GCM,data:qdG69O1RKpjod0VAOF9Wi18Uodg=,iv:Tn68WHJIV2xnqmLQ2q70ypyTcbFYvmtOUkjKO38NQA8=,tag:xd186bLyyJHjNukeM0W0Yg==,type:str]
    PUSHER_APP_SECRET: ENC[AES256_GCM,data:WINe7/f0cgVcuJAAeL6PletfSoo=,iv:z/Vk4Z024cyUbE/viiDwXNd2vXKjY8zitngUBu4NRaU=,tag:mT5soBJL+fs22JTvm3Jrgw==,type:str]
    PUSHER_PORT: ENC[AES256_GCM,data:a6en,iv:/MFltpyjca5QAgf52kcyYrrH+hCd3nzZYXoycDcojY0=,tag:Iuy1dT4Xegb/LB/t5PQ77Q==,type:str]
    PUSHER_SCHEME: ENC[AES256_GCM,data:nqKF+Ow=,iv:C7qFWy4UbNjR1WfQhcI/VM1+Jc9cg2c8i1y6bbpYSnU=,tag:LPwbDDP2HU/bZvhMUfoQPw==,type:str]
    PUSHER_APP_CLUSTER: ENC[AES256_GCM,data:GYvs,iv:GiWq0eItPryQJptdwCH1CagkxpcbQhuHtGZd3kq6uV0=,tag:7njXtwLWrB56TzQLcAXNLw==,type:str]
    GOOGLE_MAPS_API_KEY: ENC[AES256_GCM,data:XkHt5H8ddY6woRz2hot/atKFv8lUXpJksMuj5y3fF4f8ity/6X/a,iv:hI4YzZGrtXNX5Es7FaeunGwLnQ1XrQP04nWz3v+sLBg=,tag:mR5sPx5t1l3J9Aeu9JE3mQ==,type:str]
    GOTENBERG_URL: ENC[AES256_GCM,data:H9XFZCVnaYLoGrtOYpez7g4jvDFB8IfN2qXusg==,iv:cClbQ+715ZBj4DwCBK4R6RceCZN7cgRlL3bSoGYdPrU=,tag:OpnKfn09DspMxFDFutOQaQ==,type:str]
    OCTANE_HTTPS: ENC[AES256_GCM,data:pSXflg==,iv:KLa6KzQ2g1g5sB+mghZrTVdz0Ak3FFz8Ld9h+aRrn+I=,tag:ZaevfSEoluUZ8EOw9tsh4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mfp32e7fyypeyfcp6x2zhh4hkym9ra6fyv3g4p7n3klrepefx3ns7uq276
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxcjB1OFJRc0h1TTlyNm5w
            Ri81SE82Rkd3VjdvT1BqR2N6ZWlaYlEyc0RVClRqZnhJYmZrMVk4OXJ1SDNlaUdL
            RFBaZXRBbzJvWTRsZ2RLc3FNSlFKSjgKLS0tIDk5QUtscFU3alVacGlPUWk2QUg3
            bXdjY2xXMzZuM084NTB0Y1YyZm9aRzgK0ctAxatfihpIzkWHz0A840iZenOIeYQ2
            aAwB/OegDSguEj2xhjKb+ZrjCUimc7H74Wij3YaUlAFTG3Tql95xTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-15T10:16:52Z"
    mac: ENC[AES256_GCM,data:kMOnYmte+6tQZyH8yJy/PmwxlX/bRY0PJw25aFdVesDRr3FOfdcWrpqyQs812PdX2I1QR3+NieVKba4DNnpZyZGAQBkr8Ew6aHlChYN8rx/cGTQ1L+fewyPA4BcQEx4N+76DLHn9r6fkT72YOCbqjmYMXEBz7nmP5ximHLP2s5c=,iv:/5trB62PwAmu+XdzOEgyEfWFp9Ok9d68oH8C5ucrWoM=,tag:KHaeHa4IxkQ33YnWOgZ8Cw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
