apiVersion: v1
kind: Secret
metadata:
    name: portal-secrets
    namespace: portal
stringData:
    APP_NAME: ENC[AES256_GCM,data:8Yrd1NS+jH20IeDvnTDP,iv:rlUVz/QxRiDKDreLwkDM0bFcbRpksp9gnJrNTHRzLZ4=,tag:ou4kYzzJs3nYyS0CFdMZEQ==,type:str]
    APP_KEY: ENC[AES256_GCM,data:C9mtQ9wpFnjDoCxABzQv+tSVbrELts1Wpm7EwYCncJCsY6Xz4dzM2Oj+UdpOjYtObPxo,iv:9oigWJTUYbD2BeYX/qskJSzbMVIZbnBDYy2lx65svW8=,tag:Y2grhm8HbVqdUMeIEC5aZw==,type:str]
    APP_ADMIN_PANEL: ENC[AES256_GCM,data:FP1V4KVxiQRtlFC9UXBlgTDrZXbgVQ==,iv:WGxonfUsV08CtY8EUDESlzM4xLsECuQq9ilM+HPaMds=,tag:M1E5ynpHWD07Cbhe6c3Z2A==,type:str]
    APP_PROVIDER_PANEL: ENC[AES256_GCM,data:dHY/l7zKbVJ6X2X/8OodlA==,iv:P1iVvbszMcensgt/LkVnXqnfYc7iYWVfTLkJrpJJ678=,tag:ZCv35wrZGheI6wqtY4cAXA==,type:str]
    APP_DEBUG: ENC[AES256_GCM,data:hli6YrM=,iv:jXQZHTw+GEVNrUzMo/rNR2XEuhmdynuihel3RzdETDA=,tag:Lb1fdQwTMgsh4FmpRJE88A==,type:str]
    APP_URL: ENC[AES256_GCM,data:Fy+37KADz7VTzSXqN/8kFbSv/xiixmBf,iv:suSXdO2StwT9GTMfQtKETOm01V/ohQQoNDN7xlIwfGU=,tag:rm3ho7lZ9Hx/MKdbC2l8Gw==,type:str]
    LOG_CHANNEL: ENC[AES256_GCM,data:7wkj2Ry4,iv:TwCabq5rVG+0QA2SEGD0PFsDicja7j9ASK1wkHapSDI=,tag:9CTSZzi4k9S8FI7ojJOuvA==,type:str]
    LOG_LEVEL: ENC[AES256_GCM,data:i3CY8ZM=,iv:JFjFDZ59wal+nymF2/r+m38pC1tXiaHlV0VWSyvSsvs=,tag:k2R9DlyGuAqBKDNZVNEQsw==,type:str]
    DB_CONNECTION: ENC[AES256_GCM,data:MN6PAQk=,iv:YQmS0mL9e5s/b3nYHUFnXikKaG+XQXr+i3C/EN5Nk+0=,tag:xB0V5rnyV3E5gLLBX0wfwg==,type:str]
    DB_HOST: ENC[AES256_GCM,data:5MVTZjRuXAVH4IvwyvZGf0ygg+3boZTn6PI=,iv:Ruo+bKJioc2QxE696koC8+0WHJbMhrp9x4HyFswq2hg=,tag:PEKZwAbozlRsGIvrLNmq3w==,type:str]
    DB_PORT: ENC[AES256_GCM,data:BgI7sw==,iv:iBDv44H4l6YDh6krvi73FU/dqoUjUp07Lf0h09uPb8I=,tag:JUdMRyc3kkJHAJz9Bu/HeQ==,type:str]
    DB_DATABASE: ENC[AES256_GCM,data:vl6gto3T,iv:02fiHDgU8npYuqSDffY4u8sLsBrZV/2FMEsYFjBFKG0=,tag:8rQYd/zeZ7+zV7bfdhUILw==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:ekjZrkAD,iv:Wk10dpnMon9miAX+v2vWhMvuVE7itK3MnsWx3vTbB5s=,tag:5a1RO+DBHc/p5G03BvTKQg==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:gZ7GBqDhW2/wBkacqoB1t9qM1b2YIv2YxjmMPZhWfvHrxjy6KcEP3B/bcPF9KEX//FTrcNm5P+lhIUyYq00ay/a1fB3y7q+2Xo9LvFXTt59l2iHrmmqc3To399AqaQ==,iv:WPGQxUYEuThM+kJKkAj/uegyzbOUgWbzTprLVibmTmo=,tag:ivZyL8AS1zky53JCWhLTBA==,type:str]
    BROADCAST_DRIVER: ENC[AES256_GCM,data:syhu6dA=,iv:c9JBkNTmswnZ2rWPRsmW8g99jrONML4eS9vbQU8YSOA=,tag:ptahaD622I6I7cN65v+/sQ==,type:str]
    CACHE_DRIVER: ENC[AES256_GCM,data:G0HOk+I=,iv:rQODhRwPRzB0kEPWOH+DuA1Xj1Azubcs48Lln3LlH8s=,tag:tI6LgZNtkviJdaOyozg5Bw==,type:str]
    FILESYSTEM_DISK: ENC[AES256_GCM,data:8tRyp4g=,iv:klmpJPM94mXUQ7rTAyYwkxn7lxomMF5oWsSNEyzjN1E=,tag:C8YEQnnUp5UMx+2DzubClA==,type:str]
    QUEUE_CONNECTION: ENC[AES256_GCM,data:P8wtZWs=,iv:0Imerypzz5NQXlqi+WacDXCtbjI5to0EEuUx3oWo+Y0=,tag:t/m8wmTnlDNQf9+qX430Mw==,type:str]
    SESSION_DRIVER: ENC[AES256_GCM,data:7h0FnBc=,iv:JcpSsYHdscumeo3R9XB8oTUok1SXwO9B1wyYv7uRujI=,tag:+93A5V4MzuHv2L8TkaDqFQ==,type:str]
    SESSION_LIFETIME: ENC[AES256_GCM,data:YBWB,iv:TMaCI5hiDzzIM6L8+boh2Zzhvwgw8QZIyJZcs4V3Hwk=,tag:rtIRwabBsP0uUxMY8Gz1rg==,type:str]
    REDIS_HOST: ENC[AES256_GCM,data:dI+w49t/mrYwa5OqkwFV7iT89A==,iv:MBYV49kKXXg+9unaruHOzPDYDUpRuY+UdmnxBtwOHOk=,tag:DDa8THwpvrDcyVT8RFBEHA==,type:str]
    REDIS_PORT: ENC[AES256_GCM,data:aArskQ==,iv:9pHjD66hSiWr4PpBqbuWWYFupN999nMfLsx843GPLAQ=,tag:4kF8c4TG7u4WJxVXqYVZiQ==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:zY4xWEj+ZcJeWu0S+Pow3mFOryEPopVCykI7yqO2yCY76HajZTOBgRxw4019FCf0gyw1IjanQO3amwaG/Vmzt/rf4Vr0rWaso7fm53jm2ZkD7bdz/H+gOOiNHK+QGA==,iv:ilHNzjMkcva9QHrsZrAw28WFmi7CQCoWU5Syeoz6Szg=,tag:yecJ5xRJys94OFJMonS7Tg==,type:str]
    MAIL_MAILER: ENC[AES256_GCM,data:x2sk4w==,iv:uLzS128v7mE+fKhzfM6pkZreBFSm7UzMtR61tKCZK8M=,tag:vbsXr1YLsZ/fWQ5vRjj5Xg==,type:str]
    MAIL_HOST: ENC[AES256_GCM,data:rcXF1VMcwxxkktssKTY/NA==,iv:jo01EpZSQrraFxnTa8UHFSD4Q7WOdvjjDFdc8OFw4eg=,tag:5gJIM+JukKX4E9Ih2d9vxw==,type:str]
    MAIL_PORT: ENC[AES256_GCM,data:8/hcjA==,iv:jBQ9TNlZz9sdKW0CbdLgymruUA/iwwDJaq/9rEIfWoA=,tag:bKRrO4FX0lPpVPWh8UZ/lQ==,type:str]
    MAIL_USERNAME: ENC[AES256_GCM,data:Sx/jOQ==,iv:7FCoNyvCMzRRxPE3LXXO7GlVFTFCgYHyIPtkB/dxYCU=,tag:UrwRNwGaNM9KAwQCMBbVtQ==,type:str]
    MAIL_PASSWORD: ENC[AES256_GCM,data:gHvxWQ==,iv:DhUnzAx0+VQfhrsn2EkHrsnttvIF4ttojGoxrPJr/y8=,tag:bqfR9FzX8m004ZhkJ+WGVQ==,type:str]
    MAIL_ENCRYPTION: ENC[AES256_GCM,data:ze53hw==,iv:usPM66l/JZSQFxcV3FuBmcZD/WV+0e4sxK2XZgu72dQ=,tag:Nmbz4yS2md3yM52aXXWTDQ==,type:str]
    MAIL_FROM_ADDRESS: ENC[AES256_GCM,data:KpuHH3iSneJnnA7Ud0MVqA==,iv:E/egporhrzyrTap317t9/x9M3+L89+/zceHCCLPjW1E=,tag:lE2f2VaASCalveUKzmwWAA==,type:str]
    MAIL_FROM_NAME: ENC[AES256_GCM,data:46kdc+op82iCfIXk8Rae,iv:vUd+NeLSJ3rAf1FbYGrVjFIDMoJNtcFeZgcnXJvbyfc=,tag:3CZ7osIX8KHfC6dk9ePW7w==,type:str]
    PUSHER_APP_ID: ENC[AES256_GCM,data:8Flx8HcDqQ==,iv:PcGJlfK/Xow1sjLWWqVRF5R/BSZqfzRwV7yx6tiEvUs=,tag:Skrf1iOw1JblWMCtU7nJdQ==,type:str]
    PUSHER_APP_KEY: ENC[AES256_GCM,data:lFCpRmMHhiVU8WkaEHsCZWAWrMo=,iv:jOHOk78lOILv8REIioissmADba7Nu3ofKozvejpAMnM=,tag:MKu63P9cw5+l/oiY6QzCpA==,type:str]
    PUSHER_APP_SECRET: ENC[AES256_GCM,data:5vPR+qad4IWoNHES3HSwMMU9854=,iv:UGXaLXrWJsRRZtkMIJlxWysW4Sdh26Cc0/VRBknBJto=,tag:qzoRY/9dKN6qxP99fkbtwA==,type:str]
    PUSHER_PORT: ENC[AES256_GCM,data:zRQP,iv:oeGB0vjEkcr9B6d3qOQK/fW0qPIoWWmGYrqDxQsBVWE=,tag:F+SYCPAwXOksCCg5oGkobA==,type:str]
    PUSHER_SCHEME: ENC[AES256_GCM,data:aktypSs=,iv:jQxEfdXMyUGVbp7uburSqpoFv4AkFkXlcK7cNcX+Img=,tag:zCuvbV2BpBqpNfZLrfAmnQ==,type:str]
    PUSHER_APP_CLUSTER: ENC[AES256_GCM,data:EjtH,iv:q3Q8EEW9K5tYwDuErH8FVK629fbvRyymDhH3jwSHM14=,tag:RX22EHcdolJOMQVbrF3zNA==,type:str]
    GOOGLE_MAPS_API_KEY: ENC[AES256_GCM,data:ySRI56c0amRQNmpNEs/ZdyYPUJZMgcMNFvyxJZZYFSDtSJN5xJve,iv:tjDmqt6ETYCOy+6+2Alq1+BhqfXxPouvkSAL+XBbM98=,tag:iIkVmly/H8e57tqkWjjp1Q==,type:str]
    GOTENBERG_URL: ENC[AES256_GCM,data:DMyCSnVnAQ+/QTr40X3GE+v5kqsthex9Rx09UQ==,iv:1vY2/S+8TWdoideqxukQs9a9jQueGlB68OQGIgSnBx4=,tag:241GGYwMbTUxCBJJqQ1Ppg==,type:str]
    OCTANE_HTTPS: ENC[AES256_GCM,data:FHrSmw==,iv:QyYKo/tVTx3iXE8T/RpAda5CoCsAshFuBgQ+vPaCsMU=,tag:bKY0nJQafzTsVVnfZi0seQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mfp32e7fyypeyfcp6x2zhh4hkym9ra6fyv3g4p7n3klrepefx3ns7uq276
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5a21TeUo2SWJ1UkhzM3dp
            L0tKRFhuU0w1MW80UEFwR1YxMjFxYzNHU2hjCkdYODU3SVFQN3VLdXJ2ZnUxckNH
            L0hWMnJHTnY5VHdMeTB6dzkxL3hRblUKLS0tIDJUREJWdVZFSUFVMk81aFllUlEx
            eUpwZTRCa1ZCaVFLYnpqOWNQQWtMcXMKk/EjwDgwd6NcTdoFI42gofYkZMNniB3d
            SwyfGLZ3QOPhMBkU4021yHy7tDT9cCo02muLG+WIkHIDvcLCtNmxuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-05T06:24:43Z"
    mac: ENC[AES256_GCM,data:0/zgDLYSv827rhMyczgJYD2tsc2gnQiT4VDoLjyqh81mwL457DOnm8uyEXjAsPrK3kvxFLgCGN6AvU981SIOx9PEWBUTC2IzaHKBxdtj+PPPHT7O12KgJ0/Bvue2f3cg3AGdikLGgitLWYekm1uTW55yqMWGqXUQGWJ+VYzZ8tQ=,iv:Suh9PBaSW2oKqkf8wGcgr8WY+nhVnvcmU13Q5WVBKLo=,tag:Op3LURJt9SncOIftxTLFjQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
