apiVersion: v1
kind: Secret
metadata:
    name: portal-secrets
    namespace: portal
stringData:
    APP_NAME: ENC[AES256_GCM,data:MpgP0pkJwUq6uC3mesNS,iv:IDbGTz8BRchtGNjdY+jgstwWbx47l4LnKOcJv8BFFQ8=,tag:43vxpyTSAGmjccO/iOLDUg==,type:str]
    APP_KEY: ENC[AES256_GCM,data:fFMrMoF+E+l0UR1CSy3W80Vk5TNtRvojI2LV8GLpw9OA43Bx3Sns/zh45xQGPeTwCvtI,iv:67CkGRt8CQj5JoPI6H+8cVStHbmSE7brat0WXNP8pxw=,tag:fWa3xWB+jgoA9TAnOZ8i/g==,type:str]
    APP_DEBUG: ENC[AES256_GCM,data:sqzuAdY=,iv:LZLfOdHi5wBUxjZmEYTICu9feSQ70/Wy43timg52WOM=,tag:NfL65LQHaul/T5zEdtqPWg==,type:str]
    APP_URL: ENC[AES256_GCM,data:5z9zY3yrFUpk7ZMEr4hZ8L+FPChjmBhE,iv:zwWDfdOjl9yJrTI+p3vXlAC11Allf16Sya2bwe84pEk=,tag:r9KVzL3cJsWQ5QY9qo7sCg==,type:str]
    LOG_CHANNEL: ENC[AES256_GCM,data:zffxD75X,iv:4xr+ucrcAUGGTHMHKJItDHdxvoQXZnVwPIqt5w3nvOA=,tag:cIIZaNBd6d1hjGIIlIuGjw==,type:str]
    LOG_LEVEL: ENC[AES256_GCM,data:8wX41Lw=,iv:Va0oYxhCfTXE4Yt/7U6ktE9PFlWm1NySRDNaMN/aoDs=,tag:Vve3nDctTkHz5OC8OERwMQ==,type:str]
    DB_CONNECTION: ENC[AES256_GCM,data:Dp1r9VY=,iv:/bVgA+7R5FehcDSPig2sflKiKrqdrKqFtQIpEeqz9LE=,tag:lbofampJCsIUbvehCnipCQ==,type:str]
    DB_HOST: ENC[AES256_GCM,data:3v5N+Qrd/KFOjJWXcYPgfYgviExAJlmbOKo=,iv:xpFeWRV2fAK/a25tB77ZnqKCRidAcvGrZ5lYgk9QADM=,tag:ye/FCfYnGYJR7CMsVp+T9w==,type:str]
    DB_PORT: ENC[AES256_GCM,data:M9Oe1g==,iv:8pqoM4OQP9EXk+GFPahgBWmcS/GTdbxzCWjLnSd+9UY=,tag:6dzTpKdc8Q8J1q8adCiccQ==,type:str]
    DB_DATABASE: ENC[AES256_GCM,data:dVHH1pWg,iv:+/iV6hIkoFBMMqXFIRJdoaPt+CEru9zb/GUr1qy6zUY=,tag:Yvuq/HM1On3ywBy/teNQ3g==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:0ymnAUaX,iv:1mK5kPvSIXsR27Z5QaAfw9rRWj4FBWMZPAmrRl1KYcA=,tag:zvhYt1d2AcaQLIIBW5CocQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:DE8xOeuW//7SrZefKEpJf8Fmp/bbtPIkgEltXdMGqhMk3CFL5ffSNkE1xxLJ9U5Z9tCLYFhjPP3rZ+VbhYNCu2qRq8qDkdwg8V/nRm8yV67njF/5d/bWiuRtfCFAog==,iv:x0n2aIi6qhpaK8+VBnRLQXAbV31g24OkEbgM2gkfxrY=,tag:IMIhT4yC2jgEldVJoG4zfQ==,type:str]
    BROADCAST_DRIVER: ENC[AES256_GCM,data:nY94S/E=,iv:A6D+zWi09f7naxLkgsL0IxfTvEJK4LXecON4JTs1sH8=,tag:z1LLgP7J6c0hJiYkCp0W8w==,type:str]
    CACHE_DRIVER: ENC[AES256_GCM,data:P4EZrAw=,iv:eEkYlC1f33X2p4i2wMZTuzLcJB89zzm34iRVVlA9g4Y=,tag:uZcM3TRzaStylqcf6R1vig==,type:str]
    FILESYSTEM_DISK: ENC[AES256_GCM,data:ifF6ca4=,iv:qxQ209XfOjq8VrTDGFv9nJdOWcMx/6zgq8rdPmLgUzQ=,tag:NrgEsdNQF0UirFu3KlR8hA==,type:str]
    QUEUE_CONNECTION: ENC[AES256_GCM,data:Nv+VWvk=,iv:kMc0/magbxefLLPW7cDuiDyeRj03kuj6xXkBcxRCH5Y=,tag:Z8lGl0aE6qkxpBG5NGoL6g==,type:str]
    SESSION_DRIVER: ENC[AES256_GCM,data:8Nxt3rA=,iv:Vz2D7teKQM3WZK4yiON9haUDsr9dwmi0fd6aNPCPd6Y=,tag:fLbIYxV1Um7nL8CE1+7f6g==,type:str]
    SESSION_LIFETIME: ENC[AES256_GCM,data:EQRm,iv:FWx0zfMlDnnp6FbrufmPnVZGZVIkHkySqnI4kWzFzos=,tag:mBsC3KFD7lSpjQ4ycGqsZw==,type:str]
    REDIS_HOST: ENC[AES256_GCM,data:3lXOhDIWQuaWTArHK1CqxEeZ,iv:s5l7eziCh+59csJAuSvGwTxP7u4GJC67blZIA1vX0g8=,tag:t0bUX5PNQIa7Yh/ome104A==,type:str]
    REDIS_PORT: ENC[AES256_GCM,data:PxXFtg==,iv:0Z7V+m3lA8JenyhJM4VohYfPes662qZVCH83/fIXq/Y=,tag:UQ3/OWvHkjNmVGwOG8K52Q==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:wCkqLfH2LfI/szifEDUp2slIOZexzA4rA2C3zFDwye+zSwIXqqSsCpiigG69obDyMFMbNqdxCddgKbJN/+kvdEasO5ClYrod6r3YUuIFZDXIxkfY17yMqy+I+MzVZQ==,iv:FRf2o9CZHonPtlCQXpOkMuMXNO3VODpu77VFJFm1Lfk=,tag:KN6SXjOSxng+X/QnPXa61A==,type:str]
    MAIL_MAILER: ENC[AES256_GCM,data:Xc0pkQ==,iv:kZYD2hDhd/FmC8mcjBk1wJPb4+Bw7EbXoEh8j87StdM=,tag:cKMAL7twxvbnjh6nGwc2FQ==,type:str]
    MAIL_HOST: ENC[AES256_GCM,data:g1wUX9vlm2QkhKLeUT51fw==,iv:Dp8YryMpk6ZYQRNAWt7Tl4qWlBJh+ApLpbNOnUeiTdg=,tag:rj4ZSZs4OOt9uhMyYwkOwA==,type:str]
    MAIL_PORT: ENC[AES256_GCM,data:u/hGGg==,iv:bAe2mWuDzHd2XP4IwmQoXciP8vI3Z3vqg/EkVI4eGRM=,tag:sp9EYyBmTHBSS3LvqezU2Q==,type:str]
    MAIL_USERNAME: ENC[AES256_GCM,data:uHDIPA==,iv:MjDWCzV6dEsI0AQDveR60/DIaQ1qV7oTlkGUpHbzSKY=,tag:5YjEw2T7W84ZmNrAE+UEwg==,type:str]
    MAIL_PASSWORD: ENC[AES256_GCM,data:W0I1YQ==,iv:MV4wrFCF/tOz9iSo6VTNR31M5tSAzu2dRshTgi8Fcys=,tag:jAV9ZjeySfIZ3iJsrfbsAA==,type:str]
    MAIL_ENCRYPTION: ENC[AES256_GCM,data:j3V/Bg==,iv:T01wL9f5ChdybW7iztOvFCEcraZqASqwTHQLM4QxtTs=,tag:hfBK4Pqp9ZvZHcdoOOPQ6A==,type:str]
    MAIL_FROM_ADDRESS: ENC[AES256_GCM,data:oL6fgGv6puEK4kl9ZCrvrQ==,iv:/iVyS9yn/5m/YQS0/yPUT8xTNUy7TWTyPvjuTrR8LQ4=,tag:K85K2t14FBbY/uQUt9hHow==,type:str]
    MAIL_FROM_NAME: ENC[AES256_GCM,data:Sx0uFJEvH4U9F4JLGDkK,iv:xYyY0Y6ISlC2aaT/eM2ilRBLpkunHvMGlDdHWfSBFxY=,tag:myhE0IM+SGINXfR55iE/bg==,type:str]
    PUSHER_APP_ID: ENC[AES256_GCM,data:Co1EOQPnTg==,iv:xOx78yplGuRTpL1CEBDdkPIEjME5ROLFFCJ1oyKTHWI=,tag:JFdUxwIqXy3rs+IKzZrHyw==,type:str]
    PUSHER_APP_KEY: ENC[AES256_GCM,data:MGgC3WzrA7RA7VL3EL6HVGK+5jQ=,iv:POt/IGrqjxXt2wm5ObhizaSlz4pkpjdmMLHG8Wj24Rk=,tag:SHAhPNOYqcg8PHQgivlPQw==,type:str]
    PUSHER_APP_SECRET: ENC[AES256_GCM,data:tPI7OFLwUTn3soUSEreBlUCmASE=,iv:M3gpSuhToMqDBVB0YrfSoEhpUTQPYpUX3hcYmbKXfDE=,tag:pl37faJvEsajPzfjqElorg==,type:str]
    PUSHER_PORT: ENC[AES256_GCM,data:amUo,iv:tWfRIoQNZpbVHl3kfrZ0ACrq9X/Rl5/WTfmesi/pXVU=,tag:Pi4/DLvfl8jwWXTZ5t1i4w==,type:str]
    PUSHER_SCHEME: ENC[AES256_GCM,data:IXL7SoI=,iv:Pu/l/fCFOdEWtZOmnTXuFDrzWZcOjHB2bCzhMG09h3Y=,tag:sF18Kxeu3fqVOU6v+nBqmw==,type:str]
    PUSHER_APP_CLUSTER: ENC[AES256_GCM,data:DLDa,iv:Yu3zCAdtDubg+sLA9BL8obKdcL1QHXgN5MGwS2FoziQ=,tag:QvjBu98/J3CAjICa+0n6MQ==,type:str]
    GOOGLE_MAPS_API_KEY: ENC[AES256_GCM,data:b7VJ5+dQM9J/B76DxtWira5AKpcn7t5dxyQHJklQyl4tWpCN9beA,iv:Ad4UpeGPJerRA86YvvdnHboWD4vA+x/iOLn+f2vIIcE=,tag:nZtZ1Y4N+WZyN8yCTCeD8g==,type:str]
    GOTENBERG_URL: ENC[AES256_GCM,data:Kh/C5pyKhjn7mMZr0YJzwE+K6QRn,iv:6KnTaN8+q+sTbuhJ6GkqgRzKwo7jV7cs6UnBTR6qNzg=,tag:TVzaLKJlstky5/umOP8d7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mfp32e7fyypeyfcp6x2zhh4hkym9ra6fyv3g4p7n3klrepefx3ns7uq276
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBWHFTcFA2SmU5VDBKNzRU
            WnFnT1NsTkRkL2FOZTc0TDJpeG1zR0RqNXlNCmU3QmNKdjJEQW4xTVlDc0hOUWY1
            M0RxTEdXd1Q0cnY4R1NjMVR5UDViTzQKLS0tIDRnRVBib0dXZkxqZWJSTDF2REFm
            RWlRa3VDcndqNDlVY01oYS9YK3pOb28KaR6RxpTk7aYXWwdUiUiiEuUWlh2du9Wt
            qm2qyREnUzJO3uOJfj8/CVwqM6l9XzXYZZzatiQvIp3H3Ff+l9+dnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-04T12:11:06Z"
    mac: ENC[AES256_GCM,data:cyX9mJO2juTa/PyYOX8TgBe/vpBYraLI0QAZ8WMcgGxWzNl2tiBcVLpqMa8MUW31T7fbUce7/r31WDYLWFwRWF3VVdburoYt+o9/US5BkCS7h4cM0AGbCdMbuYzYlp5D/xoMoDsEhhWd8KDKq+jsuyjO+OQQSJGFSst6/UcYB6M=,iv:iM7vOWsazLyNfMFBWuWJGLpWBerl022ZJDvDifx5POw=,tag:hEZv54eF8b4CuLRjTe46Aw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
