apiVersion: v1
kind: Secret
metadata:
    name: portal-secrets
    namespace: portal
stringData:
    APP_NAME: ENC[AES256_GCM,data:vjy1eiRU3XAnWJ7lCY9O,iv:yOZq4Ygsvpn3M3lZOee4eWAn1s8bhkK1KZfKQEs1gVk=,tag:XWKoQwP2JKUssAQ83yZjhQ==,type:str]
    APP_KEY: ENC[AES256_GCM,data:Y3bjQKxVTCFnVQQMzT78/lqEWRjxEdhDPp2LpydSjLwhqnlugn/65cnmHL3pF6i01eyC,iv:bCbpGaBH/Tpz1vnbAuG3Wh88YbsPrttk83dnsCDee5c=,tag:Hldm4xeg2CljSo0LQYCkKg==,type:str]
    APP_ADMIN_PANEL: ENC[AES256_GCM,data:00tkwdhYHHKNK2jcwmjIJRQk0e/sag==,iv:kPj2qX2PE4SWLMDlNZKK6FkGPp0N0KW822Gk61dORR4=,tag:NFQx9sSY3EhuKGJVXrTXZA==,type:str]
    APP_PROVIDER_PANEL: ENC[AES256_GCM,data:Fj6rMlsHd/+x4YAvE33w46bCU77A3A==,iv:b5uWx0rSwawaOpkgU+GbrA7Rl09XZyCUc/v2htHPoHM=,tag:A8sbYEHkmdRvBltrMfMeJg==,type:str]
    APP_DEBUG: ENC[AES256_GCM,data:RIdnt24=,iv:bN9eI4gDn1Fb2pqYJ9GtyGkT59oantcaSA707U4e2CU=,tag:Jh33Q7+n1r/VBUrr6vHwxQ==,type:str]
    APP_URL: ENC[AES256_GCM,data:/xaEaeTQivTFFBAxYKCghZgKTeuIWVbx,iv:5sDr7Qt75J1eI4YATisCW0dfqrvBLvasuZOzJwmuKUM=,tag:DrhVm+4hDHEFhUtt9YFuEQ==,type:str]
    LOG_CHANNEL: ENC[AES256_GCM,data:HwxdzwdF,iv:u23G1sWIWuYO2A/cwt6mZQxIl3c1v2PVhqxQqSGIE6U=,tag:u8yAX451ohb3YChGPUK0VA==,type:str]
    LOG_LEVEL: ENC[AES256_GCM,data:EXfn1XU=,iv:SP6inhEx3xk9DL+7ZDZICWcctBBfD9UkCbe1rDExR5M=,tag:4yViatyaYCruZBti4Pcqbg==,type:str]
    DB_CONNECTION: ENC[AES256_GCM,data:HLp9yyw=,iv:HKLqFduHlrjLG/jSb9eEsOz4uxuWAhaB2ouVuZ71+UQ=,tag:qKu5iBYjJ2ReqbyF+D4vDQ==,type:str]
    DB_HOST: ENC[AES256_GCM,data:DedbEA32Rtn3MMtzx1M6CfgqygGwCYqjw7E=,iv:juNqLifm0vkGI5nGZqv7CTsrCV1ZBeHl9JJFxduObJQ=,tag:O+PFO6LGj9btbDJD8aEdlg==,type:str]
    DB_PORT: ENC[AES256_GCM,data:Rs5NXA==,iv:f3J9lUwDTX9wT6bzzbGyj8yVu8kza1tVFZzEoUYYn24=,tag:Vyu0VuUisezS0YkWDbilGA==,type:str]
    DB_DATABASE: ENC[AES256_GCM,data:QoFWptia,iv:N9JFtkcl9qXspKgxOmwlFFD/J7KEcxZ9yJcsKFfDxkk=,tag:DMYtgmkJ7yO3qVleU1CzYQ==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:ZzdFT1IJ,iv:bNqyVVAc47dT9mE7OUdh+aLURgZlDKNYwsp/WTdwGw4=,tag:AbIAdWSWyUK3T3mwTgqwhA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:KbFc/ibyFWgptYjlH5qH5BGuEfsR4kZKEKkjMQ1WpiqM3m9GjK/7O+obBlbddypPk7sVrjwByv+zKfdDbskQ1/9TmutHcKafBN59G5GibqYw9ApSvxX6IGtQu6BiKA==,iv:qHycxAOKuceLw1YcJI2dn9xwru9QrDcszT/GqhqhNAA=,tag:2a6bW4xeLjQkmQt6Ads2iA==,type:str]
    BROADCAST_DRIVER: ENC[AES256_GCM,data:sUQECUw=,iv:b3pSVdv+0/dIdVnlssb8pMGFsNzNGnEpx6gh4fRXqgQ=,tag:wpy99gj6E97ZlTxEqfNWhw==,type:str]
    CACHE_DRIVER: ENC[AES256_GCM,data:vs54PsE=,iv:GxI5q6ovOxKSQKxtr9khlho5XY6S7oHDCXKrfHj4pkc=,tag:wf2dWQyb7W3WOgrPeeMBIQ==,type:str]
    FILESYSTEM_DISK: ENC[AES256_GCM,data:DA4gTV0=,iv:iQOZjKo3vBtLwtP/nOSXc8tV8zeIE9BHvcrPIsxoDPo=,tag:cRC2enW6ywv3zK3uTn+PnQ==,type:str]
    QUEUE_CONNECTION: ENC[AES256_GCM,data:XbSPJi4=,iv:881q+l+YFiym6nY8jPCoMHiIHnU8AaviFM8UMZl7kI4=,tag:Yyr1dlsDHuI7hf5mhnl6Gg==,type:str]
    SESSION_DRIVER: ENC[AES256_GCM,data:QUPdU+k=,iv:gTTU6BjESG9u/6RFtUCUHuQvRojjDngFYnCL52XtGq8=,tag:q/PfESLUG+KRGSXfuKE27g==,type:str]
    SESSION_LIFETIME: ENC[AES256_GCM,data:ET+7,iv:G+9EMtQrJSFLmogYJqo6J26OkEE/FMZ+roqCqasoLmU=,tag:SRGFPM3LQao8/3/UlEegUA==,type:str]
    REDIS_HOST: ENC[AES256_GCM,data:r9oQSqRyI1bsGkecr4qLXV0crg==,iv:tSlt7f8IsGNQW94MuaqGHjAAQJ5zqpG5cwJ4+eL+Qww=,tag:cy4jtM/CtKfT9FcmvKSpqg==,type:str]
    REDIS_PORT: ENC[AES256_GCM,data:8PD0Vg==,iv:i5SgeTaEGCnErATjvo4LFfcB04b9nIlnWuKamRFeRq0=,tag:nwM3n/nKyR6hHJyBN4NZrw==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:L+jr3UBpJwmDRg+Pm/Z3TqEmC/JCP5VrGnwwo2F04AkLqcVU3n0W0ewey4/QQ3M/YcYGSUUA/cGHcy5x9cfSxnoOq+gF3geQ5SIPepqMW1DhJGj0D676g8DLCOD4UA==,iv:QrxH4f2fMJVpyDKQVEDxdgQxAREKCQsoK2jCjG6goOw=,tag:Cf6zuW8IrMwCafdtoP0j7g==,type:str]
    MAIL_MAILER: ENC[AES256_GCM,data:mj+6gA==,iv:JGdn108ptG4sSE6QSfLP18MIUGSwGwhXD5XvTGf7nDw=,tag:O0o5gu5fb3cYQWGrOH8MKQ==,type:str]
    MAIL_HOST: ENC[AES256_GCM,data:2+YX/dJREdbHnuAXWtmXrg==,iv:3kprrZqAlKTEnDQN6RPIL0xYKT7WKAWymfjzG1dTSqM=,tag:1FdU0iD+2lwOgl24f8POrw==,type:str]
    MAIL_PORT: ENC[AES256_GCM,data:PttE9A==,iv:jw0RtQikHUBDBCSAJdO8brOjEyAuZLMWjhvUizzv9Dw=,tag:kbZiHR6Dd6YnCu/zcDOvoA==,type:str]
    MAIL_USERNAME: ENC[AES256_GCM,data:2r3inA==,iv:DGnV2C0sU8rL4tpupLnNvwe+A7iqi2fOpljTEFSQg4Y=,tag:8sfDqD8ggVx7+J7oLB9IjA==,type:str]
    MAIL_PASSWORD: ENC[AES256_GCM,data:RJCewg==,iv:fvO9QqI/RKyd/su4VZ7XId4o65xOtNCcxZrizPUtrGY=,tag:Ik5izT7eENWWPmaB9R4PQg==,type:str]
    MAIL_ENCRYPTION: ENC[AES256_GCM,data:k6RBjQ==,iv:sHU+giWD4dh2AHgwJ1aZ5GlxAP/gubWoRruhn7iIzKI=,tag:PXKCG0ZQVZ24OOihXMYncw==,type:str]
    MAIL_FROM_ADDRESS: ENC[AES256_GCM,data:x6LW31a2FuX4hrmNMtRCrA==,iv:p3W6D7B+OlQOZQo9xN8p85nVNIhFJoU/Vi2SAQP+LMA=,tag:JmNKiuttUpGIrNaloECP3Q==,type:str]
    MAIL_FROM_NAME: ENC[AES256_GCM,data:euqSQ8mihPiwAOmiDD0a,iv:UDpPltvfBN8+Tn8quNBTLWVh4RIDxf6Qr4Rw4LIe82Q=,tag:ubEilGziMqX7F6SbS5IuFw==,type:str]
    PUSHER_APP_ID: ENC[AES256_GCM,data:vDlK5e+GSw==,iv:s4OjyTfG1j/awk05P4nquv0f2Nk9iR5l5MBWeNLQY7s=,tag:Rayu+qGXX19lUz1n230E2w==,type:str]
    PUSHER_APP_KEY: ENC[AES256_GCM,data:UZsu21h78u3ZV8tAiNE5H0uHstI=,iv:JfeLFXVwnYOo56lrQ/fglbLNL1IS0Q/13nlgTxVdAhI=,tag:8O/7lMAjwVsuqa5ndyzV7A==,type:str]
    PUSHER_APP_SECRET: ENC[AES256_GCM,data:aiPFtz+0Y8CyMmSDquMlF31Cd+k=,iv:s/xrCiFNgNgWXTsXczzWzp9RYinZwVEss4BoCMNIaRs=,tag:O5nM/lpJMjUccfmNDNEivQ==,type:str]
    PUSHER_PORT: ENC[AES256_GCM,data:VKNb,iv:LO3eauIbtcutob7sAouDe9Beb5qMZerJ56fYDzishQw=,tag:c6/gRX54YHLhKwXRinIeIg==,type:str]
    PUSHER_SCHEME: ENC[AES256_GCM,data:3B61FvM=,iv:guoe1PY/x6YaG8YwFSPtV2211PguiKhqCHLMHNxw1Z4=,tag:2o/0hj8KdEnLTFFBnEz44w==,type:str]
    PUSHER_APP_CLUSTER: ENC[AES256_GCM,data:hYsr,iv:uqbsi6HxlT78TzpDotovN9SBAYpObfM7tuzms53kiOE=,tag:0UDf/7x4MxUC96U10fqk6g==,type:str]
    GOOGLE_MAPS_API_KEY: ENC[AES256_GCM,data:eqQTEkZedQ5s5JXHj3YMTuoqQTcODVCA2MqM3+k08HSzHJ9sof9+,iv:XvFYzN5n+E0w2KHR/lSc1jltOwKIDQQGTLUr4KNJAtk=,tag:OOxnfo2wavyIxhsuT9Stgg==,type:str]
    GOTENBERG_URL: ENC[AES256_GCM,data:ELT/WLp+Iu48CIr062q7oZ66WP6dMc1b7f7xaw==,iv:OecWm0u/F4HAYw1akl7KiENbbI1NKvkVhCCBLfTTyfk=,tag:1GxvXt63iMtzzrOS5Pe+JA==,type:str]
    OCTANE_HTTPS: ENC[AES256_GCM,data:5xhZ1g==,iv:ZLOkNu9noas/knQQsynjBwbQI9VCrDeg4f8+Rps4agc=,tag:YCs3ubZYeu2bO3Iwfitzfg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mfp32e7fyypeyfcp6x2zhh4hkym9ra6fyv3g4p7n3klrepefx3ns7uq276
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuTkdqSkRwSTlWY1ZsVWRG
            N0QyWkZpNitFK3RqMHZhT3FSb2NiUXJscERnCmx5bFZtWjMvY1BGbzg2Qm1sbnYx
            TW5lRTVFUjFacnhSV1BhK3V5ZFZzN0EKLS0tIHNVOVNOYXY0Q05QTzJIUUZSeExH
            NWRrL1JMY1dDcmRCdnlMZ2IzU2phSmsKstfrk+Z6zZcWj31eZOclv0T0CtnVBR5A
            YThTsMoCB2r0gAJSYHv55yMuNB/1oNSjbv0tdrvkUOMVzyRYd4Jy7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-05T05:46:10Z"
    mac: ENC[AES256_GCM,data:fWJd/2o4waZ1nKckf14bHQ+m+0nZuIXnLG1tfRFN1yxm1bRhDy73Gagj4mkJ28Z9FgTHnzBkCKr2cBD9nMNVPEDHbXzpk++XE0Fu24SvWjkhACnTKhcHyLVG7v9cFiPHYv5rIMGbMV55fLyWsluUEA8p1VIp6mp2HJxyQyNpW04=,iv:VfG6kyOiu38M53iT40S2Tei8+wpDIhczQ77axy3j1wY=,tag:FZt18qlXlVO+W1cw7+8VYg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
