---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 1m0s
  dependsOn:
    - name: cluster-config
    - name: metallb
    - name: traefik
    - name: sources
    - name: kyverno
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  path: ./k8s/the-it-dept/apps
  validation: client
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  postBuild:
    substitute: { }
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
      - kind: Secret
        name: cluster-secrets
