---
apiVersion: v1
kind: Service
metadata:
  name: gps-server
spec:
  selector:
    app: gps-server
  ports:
    - name: gpsd
      protocol: TCP
      port: 2947
      targetPort: 2947
---
apiVersion: v1
kind: Service
metadata:
  name: gps-server-np
spec:
  type: NodePort
  selector:
    app: gps-server
  ports:
    - port: 2947
      targetPort: 2947
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 32747
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gps-server
spec:
  selector:
    matchLabels:
      app: gps-server
  template:
    metadata:
      labels:
        app: gps-server
    spec:
      nodeSelector:
        hardware/gps: "true"
      containers:
        - image: ghcr.io/na4ma4/gps-server:1
          name: gps-server
          ports:
            - containerPort: 2947
          securityContext:
            privileged: true
          resources:
            limits:
              cpu: 100m
              memory: 10Mi
            requests:
              cpu: 50m
              memory: 10Mi
          env:
            - name: GPS_DEVICE
              value: "/host/dev/gpsd0"
          volumeMounts:
            - name: dev
              mountPath: /host/dev
              mountPropagation: HostToContainer
              readOnly: true
          livenessProbe:
            exec:
              command:
                - "/bin/sh"
                - "-c"
                - "gpspipe -n20 -w gps-server | grep -q -m1 TPV"
            timeoutSeconds: 10
            initialDelaySeconds: 30
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
      volumes:
        - name: dev
          hostPath:
            path: /dev
