---
apiVersion: v1
kind: Service
metadata:
  name: ntp-server
spec:
  selector:
    app: ntp-server
  ports:
    - name: ntp-tcp
      protocol: TCP
      port: 123
      targetPort: 123
    - name: ntp-udp
      protocol: UDP
      port: 123
      targetPort: 123
---
apiVersion: v1
kind: Service
metadata:
  name: ntp-server-np
spec:
  type: NodePort
  selector:
    app: ntp-server
  ports:
    - port: 123
      targetPort: 123
      nodePort: 32123
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ntp-server
spec:
  selector:
    matchLabels:
      app: ntp-server
  template:
    metadata:
      labels:
        app: ntp-server
    spec:
      nodeSelector:
        hardware/gps: "true"
      containers:
        - name: ntp-server
          image: ghcr.io/na4ma4/ntp-server:1
          ports:
            - name: ntp-tcp
              containerPort: 123
            - name: ntp-udp
              protocol: UDP
              containerPort: 123
          securityContext:
            privileged: true
          resources:
            limits:
              cpu: 100m
              memory: 50Mi
            requests:
              cpu: 50m
              memory: 10Mi
          volumeMounts:
            - name: dev
              mountPath: /host/dev
              mountPropagation: HostToContainer
              readOnly: true
          # livenessProbe:
          #   exec:
          #     command:
          #       - "/bin/sh"
          #       - "-c"
          #       - "gpspipe -n20 -w ntp-server | grep -q -m1 TPV"
          #   timeoutSeconds: 10
          #   initialDelaySeconds: 30
          #   periodSeconds: 30
          #   successThreshold: 1
          #   failureThreshold: 3
      volumes:
        - name: dev
          hostPath:
            path: /dev
