---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: portal-gotenberg
  namespace: portal

spec:
  releaseName: portal-app
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system

  values:
    controllers:
      main:
        strategy: RollingUpdate
        containers:
          main:
            image:
              repository: getlago/lago-gotenberg
              tag: 7
              pullPolicy: IfNotPresent

            env:
              TZ: Australia/Sydney


    service:
      main:
        ports:
          http:
            port: 3000
