---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/cert-manager
  - ../../base/external-dns
  # TODO: Cloud Native PG - ../../base/cloudnative-pg

patchesJson6902:
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: external-dns
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: "--txt-owner-id=staging.syd.node.net.au"
