---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: portal-mailhog
  namespace: portal

spec:
  releaseName: portal-mailhog
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system

  values:
    controllers:
      main:
        strategy: RollingUpdate
        containers:
          main:
            image:
              repository: mailhog/mailhog
              tag: latest
              pullPolicy: IfNotPresent

            env:
              TZ: Australia/Sydney
              MH_HOSTNAME: demo-mail.node.net.au
              MH_MAILDIR_PATH: /data
              MH_STORAGE: maildir

    service:
      main:
        ports:
          http:
            port: 8025

          smtp:
            port: 1025

    ingress:
      main:
        enabled: true
        className: nginx

        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production

        hosts:
          - host: &host demo-mail.node.net.au
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http

        tls:
          - hosts:
              - *host
            secretName: *host

    persistence:
      storage:
        enabled: true
        type: persistentVolumeClaim
        size: 5Gi
        accessMode: ReadWriteOnce
        retain: true
        advancedMounts:
          main:
            main:
              - path: /data
                readOnly: false
