---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kube-vip
  namespace: flux-system
spec:
  path: ./k8s/base/kube-vip/kube-vip/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: DaemonSet
      name: kube-vip
      namespace: kube-system
  interval: 30m
  retryInterval: 1m
  timeout: 3m
