apiVersion: v1
kind: Secret
metadata:
    name: keycloak-secrets
    namespace: keycloak
stringData:
    username: ENC[AES256_GCM,data:hIts6xo=,iv:Oxxweh+Z0z1mOskn8rieH1uO+clnH3MgUmlU8BdK06w=,tag:qJpYcWRvEsvF0vWNjwYU2Q==,type:str]
    password: ENC[AES256_GCM,data:lIVGG3mYR34SzUxarRsF,iv:b5wtgsjwmItE7YBMePUMEaTyeZyTQKDxLwg2Q9w7z8Q=,tag:JaXyLaiLuM/OMVsLbNLAXA==,type:str]
    postgresql-password: ENC[AES256_GCM,data:atX3Lt30MYwX4n2KAywr6HJRsrfbMU4sOWgAnkIbywjBCNVoe2G15mhfNIZ1SU8=,iv:7qWxXnGnDiZ++nbIpxNIz6S1PhQPVOt72E8fIyCCzuc=,tag:wyPsi1ZPkXRgJO3U2N+KmA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mfp32e7fyypeyfcp6x2zhh4hkym9ra6fyv3g4p7n3klrepefx3ns7uq276
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVcjh4SktvQ1JRTFZnLzBM
            VXpzWnFsL0R5NmFZamNwUG5qakIvOXlIRVMwCjczMDh4VGJpNWIrRGJLaldqR1dN
            MkhpZHNGK3ByOUZ4MXVOZDkxczYzMnMKLS0tIGFzK3lLSUlQdUcyempnZVZIaXg1
            Q0R5NS9pbmlmUUh5ZkJKdCtFK2xaWGcKnchNMvO58+wRYHNlRcSzQO6COz4HyXvs
            o2F4IRiL/AAFnTW9zrZbaym0SAzMq3pZN+pbCGHQPAUNEtkBM12qLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-19T10:00:56Z"
    mac: ENC[AES256_GCM,data:8SC8z0LXuaRRWq2rga2tqdVaMUe/blEZOCyKdmTpGJ7gpsukbLEoqODbwaR4k0dqar2Vs5Ifp/p7GJ7+T08CYE2QmQdvxgEGHNMA/EUBY3aKyhipOhBSySV4Wem+8SWP6zf99eYN38TEr5/3YjRTKYlODyTVe9vQxPaYvs2S1+w=,iv:VGw+Ivndn+m4ZvluaW9RSVzoeFOBJA+4ETnV2tc2JXY=,tag:PbMxPP29mjYQhM7nH235NQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
