apiVersion: v1
kind: Secret
metadata:
    name: rfspager-secrets
    namespace: rfspager
type: Opaque
stringData:
    RFSPAGER_SERVER_URL: ENC[AES256_GCM,data:HRQGkZ+0NEnGZG+JESMiesoFA5QhQy1VCegyX67k,iv:fCavLwDT+EA7rL8NafMBmb9oPHmYjMoO5r/TcAm5iLs=,tag:VwPxyAImJZzQ/819+iPJtg==,type:str]
    RFSPAGER_AUTH_TOKEN: ENC[AES256_GCM,data:IA07ZDLOG3jxv8aGppvzbzubpPUowtkVkOWoAcc2rgpLDUPBb3jvA6Ry,iv:S6zg+wEQaHBfRZOBEBhQQR0onauK3AO9ez20Cjl/zHA=,tag:faio/RwGyt8FNMNOFIQ4Ig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mfp32e7fyypeyfcp6x2zhh4hkym9ra6fyv3g4p7n3klrepefx3ns7uq276
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZG5raDh2d2VRdk1EM3F6
            Z3JjUDNyRW9tcUlQZUpucm9xczhmK21ROGpJCkZJcVhXRGxFNVZaTTg0aFlobnZI
            amRVSmRYdCt0eDlpeEtYbXJOMzZKclUKLS0tIFRubE5QMUNQcHBDNkVxU2Ntb29J
            NzVYUE80Yk5scFgwR21pekJ4WUQ4WUEK/Fignh+oVuBV/TUR6TeNMR8Ma007Jkvh
            Zx/mqtJIC5HVcuRPqbrEHPsbmeoZ7gJED3PQUqHjPtOuG9Ui/lP2rw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-04T05:38:46Z"
    mac: ENC[AES256_GCM,data:WuGa1tFja+yuwdDO0p2xhhoeQ9gVy328tszs4SZ26saaXQdEJu7Y3zOSp7rIthGM4c1ZkLSNyHYLN4HYPt1s3JBLH3OtJ4gOvfhrmt+dErMBhZzhO9I9kCpIAtkoLFr+sdAoHYHTp9JA7XTJWwd9+rDHJ70FltOY3lY6zOnmhCo=,iv:CctIQNVvna0BNs1bijsCsG6t0eQVeS6xi1kUAyZFu24=,tag:FpTfCYjGzQhYpzdseHPjFA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
