---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: ln-au
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.min.io
      chart: minio
      version: 4.0.0
      sourceRef:
        kind: HelmRepository
        name: minio-charts
        namespace: flux-system
      interval: 5m
  values:
    persistence:
      enabled: true
      size: 25Gi
      storageClass: ssd-gold

    resources:
      requests:
        memory: 4Gi

    mode: standalone

    rootUser: "${SECRET_LNAU_MINIO_ROOT_USER}"
    rootPassword: "${SECRET_LNAU_MINIO_ROOT_PASS}"

    buckets:
      - name: lnau
        policy: none
        purge: false

    users:
      - accessKey: "${SECRET_LNAU_MINIO_USER_KEY}"
        secretKey: "${SECRET_LNAU_MINIO_SECRET_KEY}"
        policy: readwrite

    ingress:
      enabled: false
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
      ingressClassName: "traefik"
      path: /
      hosts:
        - &host s3.ln.au
      tls:
        - hosts:
            - *host
          secretName: *host

    consoleIngress:
      enabled: true
      ingressClassName: "traefik"
      path: /
      hosts:
        - &consolehost s3-console.ln.au

      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production

      tls:
        - hosts:
            - *consolehost
          secretName: *consolehost
