---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: base-sources
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./k8s/base/sources
  prune: true

  sourceRef:
    kind: GitRepository
    name: flux-system
