---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: infra
  namespace: flux-system
spec:
  interval: 1m0s

  prune: true
  path: ./k8s/demo.node.net.au/infra

  sourceRef:
    kind: GitRepository
    name: flux-system

  decryption:
    provider: sops
    secretRef:
      name: sops-age

  dependsOn:
    - name: base-sources
