apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cluster-config
  namespace: flux-system
spec:
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./k8s/the-it-dept/cluster-config
  prune: true
  validation: client
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
