---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/kube-vip
  - ../../base/cert-manager
  - ../../base/longhorn
  - ../../base/cloudnative-pg
  - ../../base/external-dns

patchesStrategicMerge:
  - kube-vip-patch.yaml

patchesJson6902:
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: external-dns
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: "--txt-owner-id=node.net.au"
