---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: portal-app-admin
  namespace: portal

spec:
  releaseName: portal-app-admin
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system

  values:
    defaultPodOptions:
      imagePullSecrets:
        - name: ghcr-secret

    controllers:
      main:
        strategy: RollingUpdate
        containers:
          main:
            image:
              repository: ghcr.io/the-it-dept/node-isp
              tag: portal-v0.2.3
              pullPolicy: IfNotPresent

            envFrom:
              - secretRef:
                  name: portal-secrets

            env:
              TZ: Australia/Sydney
              APP_ADMIN_PORTAL: true
              APP_ADMIN_PORTAL_DOMAIN: &admin demo-admin.node.net.au
              APP_ADMIN_PORTAL_PATH:

              APP_PROVIDER_PORTAL: true
              APP_PROVIDER_PORTAL_BASE_DOMAIN: &provider demo.node.net.au
              APP_PROVIDER_PORTAL_PATH:

              APP_CUSTOMER_PORTAL: true
              APP_CUSTOMER_PORTAL_DOMAIN: &customer demo-customer.node.net.au
              APP_CUSTOMER_PORTAL_PATH:
    service:
      main:
        ports:
          http:
            port: 8000


    ingress:
      main:
        enabled: true
        className: traefik

        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production

        hosts:
          - host: *admin
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http

          - host: *provider
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http

          - host: *customer
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http

          - host: demo-provider.node.net.au
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http

          - host: provider.demo.node.net.au
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http

        tls:
          - hosts:
              - *admin
            secretName: *admin

          - hosts:
              - *provider
            secretName: *provider

          - hosts:
              - *customer
            secretName: *customer

          - hosts:
              - demo-provider.node.net.au
            secretName: demo-provider.node.net.au

          - hosts:
              - provider.demo.node.net.au
            secretName: provider.demo.node.net.au

    persistence:
      storage:
        enabled: true
        type: persistentVolumeClaim
        size: 5Gi
        accessMode: ReadWriteOnce
        retain: true
        advancedMounts:
          main:
            main:
              - path: /app/storage/app/public
                readOnly: false
