---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: range-1
  namespace: metallb-system
spec:
  addresses:
    - 44.136.159.250/32
    - 44.136.159.251/32
    - 44.136.159.252/32
    - 44.136.159.253/32
    - 44.136.159.254/32
  autoAssign: false
  avoidBuggyIPs: false
