---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - crds.yaml
  - helm-release.yaml
  - address-pools.yaml
  - bgp-advertisement.yaml
  - peer-cr01.yaml
  - peer-cr02.yaml
