---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: peer-cr02
  namespace: metallb-system
spec:
  myASN: 64512
  nodeSelectors:
    - matchLabels:
        externallb: 'yes'
  peerASN: 64512
  peerAddress: ${CONFIG_CR02_BGP_PEER_ADDRESS}
  peerPort: 179
