---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rfspager
  namespace: rfspager

spec:
  releaseName: rfspager
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system

  values:
    controller:
      strategy: "RollingUpdate"

    image:
      repository: ghcr.io/the-it-dept/rfspager-backend
      tag: v3.1.0
      pullPolicy: IfNotPresent

    imagePullSecrets:
      - name: ghcr-secret

    command: ["/cnb/process/web"]

    env:
      TZ: Australia/Sydney
      PORT: 8080

    envFrom:
      - secretRef:
          name: rfspager-secrets

    service:
      main:
        ports:
          http:
            port: 8080

    ingress:
      main:
        enabled: true

        ingressClassName: nginx

        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production-nginx

        hosts:
          - host: &host "v2.rfspager.app"
            paths:
              - path: /

        tls:
          - hosts:
              - *host
            secretName: *host

    persistence:
      config:
        enabled: true
        mountPath: /etc/rfspager
        type: secret
        name: rfspager-secretfiles
