---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secrets.sops.yaml
  - secretfiles.sops.yaml
  - ghcr.sops.yaml
  - rfspager-host-db.yaml
  - helm-release.yaml
