---
apiVersion: v1
kind: Service
metadata:
  name: rfspager-host-db
  namespace: rfspager
spec:
  ports:
    - port: 5432
      name: postgres
      protocol: TCP
      targetPort: 5432
    - port: 6379
      name: redis
      protocol: TCP
      targetPort: 6379
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: rfspager-host-db
  namespace: rfspager
subsets:
  - addresses:
      - ip: 27.50.64.158
    ports:
      - port: 5432
        name: postgres
        protocol: TCP
      - port: 6379
        name: redis
        protocol: TCP
