---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: headscale
  namespace: headscale
spec:
  releaseName: headscale
  chart:
    spec:
      chart: headscale
      version: 0.8.4
      sourceRef:
        kind: HelmRepository
        name: gabe565-charts
        namespace: flux-system
  interval: 5m

  values:
    env:
      TZ: Australia/Sydney
      HEADSCALE_DNS_CONFIG_BASE_DOMAIN: ts.theitdept.au

    sidecars:
      ui:
        image: ghcr.io/gurucomputing/headscale-ui:latest
        ports:
          - name: http
            containerPort: 80

    service:
      main:
        ports:
          ui:
            port: 80

    ingress:
      main:
        enabled: true

        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production

        hosts:
          - host: &host "ts.theitdept.au"
            paths:
              - path: /

        tls:
          - hosts:
              - *host
            secretName: *host

      ui:
        enabled: true
        hosts:
          - host: *host
            paths:
              - path: /web
                service:
                  port: 80
        tls:
          - hosts:
              - *host
            secretName: *host


    persistence:
      config:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 2Gi
