---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: headscale
  namespace: headscale
spec:
  releaseName: headscale
  chart:
    spec:
      chart: headscale
      version: 0.8.4
      sourceRef:
        kind: HelmRepository
        name: gabe565-charts
        namespace: flux-system
  interval: 5m

  values:
    initContainers:
      config: {}

    env:
      TZ: Australia/Sydney
      HEADSCALE_DNS_CONFIG_BASE_DOMAIN: ts.theitdept.au

    sidecars:
      ui:
        image: ghcr.io/ifargle/headscale-webui:latest
        ports:
          - name: http
            containerPort: 5000
        env:
          TZ: Australia/Sydney
          COLOR: red
          HS_SERVER: https://ts.theitdept.au
          DOMAIN_NAME: https://ts.theitdept.au
          SCRIPT_NAME: /admin
          KEY: "MzM3+bMMpGLklbHTJGIpSCsEZJh98b4l5/13mrk7QQs="
          AUTH_TYPE: basic
          LOG_LEVEL: info
          BASIC_AUTH_USER: admin
          BASIC_AUTH_PASS: password
        volumeMounts:
          - name: config
            mountPath: /etc/headscale
            readOnly: true
          - name: ui-data
            mountPath: /data

    service:
      main:
        ports:
          ui:
            port: 5000

    ingress:
      main:
        enabled: true

        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production

        hosts:
          - host: &host "ts.theitdept.au"
            paths:
              - path: /

        tls:
          - hosts:
              - *host
            secretName: *host

      ui:
        enabled: true
        hosts:
          - host: *host
            paths:
              - path: /admin
                service:
                  port: 5000
        tls:
          - hosts:
              - *host
            secretName: *host


    persistence:
      config:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 2Gi
      ui-data:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 2Gi
