---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: headscale
  namespace: headscale
spec:
  releaseName: headscale
  chart:
    spec:
      chart: headscale
      version: 0.8.4
      sourceRef:
        kind: HelmRepository
        name: gabe565-charts
        namespace: flux-system
  interval: 5m

  values:
    env:
      TZ: Australua/Sydney
      HEADSCALE_DNS_CONFIG_BASE_DOMAIN: ts.theitdept.au
    
    ingress:
      main:
        enabled: true
        hosts:
          - host: &host "ts.theitdept.au"
            paths:
              - path: /

        tls:
          - hosts:
              - *host
    
    persistence:
      config:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 2Gi
