apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:zv4VY9YWKHBS8OLT/TzsCey/3yo7eVAFf+w31dcEMwrAvP2FujQPfHZGJzrAixu74VZ1sknk+sUUTSLTnpUPV1shTgDd12i2B/MO6Q24o197oyGiq0H2bH+QhIJAUZU/irW83W4OR6OEhWYXWvx2PuWGC/svm9yp+YLLcDKRT1G0p1HxcVxITDbYEsTSnIP/JAXUbkuymn7oPpX+rBJdPksg3UrB4syvCDEXNtn0b0V03iyG0q2e2HCLUWTp94mTUFyp3r9IVM4dLSBZe+uaKmdB+RqY3Y280/DCpcZCoAUAJYZlI4lFRoV3oxbmlU+AZUi/tqJVtRSFA+rdWs/8WeFoHs3oKhAbE2zkRT3y1ia6MYG8tOe5UTYrnFw=,iv:zgNdeL375hrtEdpgD+HiAvXuG6EQPUYi/hM3LalaFOQ=,tag:kPKYOoYZ54meNyRYYLqdiA==,type:str]
kind: Secret
metadata:
    name: ghcr-secret
    namespace: billing
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mfp32e7fyypeyfcp6x2zhh4hkym9ra6fyv3g4p7n3klrepefx3ns7uq276
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBleit3RFcyYUFaZGRzSzI5
            bVIzVUhSSUIrMk1Ka2tIak9ac25wZnJvSFU4CldLY3hOMVVIQld4U1R0Tkd0SklO
            V1VVSHF1aHZEaFhmUElHTEFFN2IvQ1kKLS0tIDlEMU1DSjk3cUV1YjRKOU11dGZo
            UllpS2kwOTVvQmJ1THNvNjY4aUJ1MUEKXAyjzxZs1mx50RQHXuaitOfdNc6a4i/p
            fIFwEhwqDibFBBLzTgpVI+eRdoG3bnP0RgbTShf5Vunc0oDPFJIrDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-29T22:58:20Z"
    mac: ENC[AES256_GCM,data:tYm+VI4WA7gjMbAzYQqmK91vPBevhkHLqwx7ibxopaRrUnStG8PFN78vdCHqnNsmlHORsr9AUfLQq4UcH+ayERh+HEVfhGQWujBYzYgtSgJRLzY6reFjBgpkgxwauscOCfdWexGyCjgllaFbGZXoyJCD9UMd2FkWjnGF9mQspIg=,iv:OK7ZEvJi7N4+O7F3USHlLDmDpQ0i6SjcEiSeheqJVqU=,tag:HePJJf88tnlk0ppFi10G+w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
