---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-vip
spec:
  chart:
    spec:
      chart: kube-vip
      version: 1.4.1
      sourceRef:
        kind: HelmRepository
        name: kube-vip-charts
        namespace: flux-system
  interval: 30m
  timeout: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: -1
    crds: CreateReplace
