---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  values:
    controller:
      service:
        annotations:
          cloud-provider-cloudflare.nicko170.au/tunnel-id: 43f67efe-4a03-4828-a68e-2c1f02f3d76a
