---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: portal-postgres
  namespace: portal
spec:
  releaseName: portal-postgres
  chart:
    spec:
      chart: postgresql
      version: 13.1.5
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system

  interval: 5m

  values:
    global:
      postgresql:
        auth:
          username: portal
          database: portal
          existingSecret: portal-secrets
          secretKeys:
            adminPasswordKey: POSTGRES_PASSWORD
            userPasswordKey: POSTGRES_PASSWORD

    primary:
      persistence:
        size: 5Gi

    readReplicas:
      replicaCount: 0
