---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: billing-redis
  namespace: billing
spec:
  releaseName: billing-redis
  chart:
    spec:
      chart: redis
      version: 18.2.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system

  interval: 5m

  values:
    auth:
      existingSecret: billing-secrets
      existingSecretPasswordKey: REDIS_PASSWORD

    master:
      persistence:
        size: 8Gi

    replica:
      replicaCount: 0
