---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: portal-app
  namespace: portal

spec:
  releaseName: portal-app
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system

  values:
    defaultPodOptions:
      imagePullSecrets:
        - name: ghcr-secret

    controllers:
      main:
        strategy: RollingUpdate
        containers:
          main:
            image:
              repository: ghcr.io/the-it-dept/node-isp-portal
              tag: node-portal-v0.0.7
              pullPolicy: IfNotPresent

            env:
              TZ: Australia/Sydney

            envFrom:
              - secretRef:
                  name: portal-secrets


    service:
      main:
        ports:
          http:
            port: 8000


    ingress:
      main:
        enabled: true
        className: traefik

        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production

        hosts:
          - host: &host "demo.node.net.au"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http

        tls:
          - hosts:
              - *host
            secretName: *host

    persistence:
      storage:
        enabled: true
        type: persistentVolumeClaim
        size: 5Gi
        accessMode: ReadWriteOnce
        retain: true
        advancedMounts:
          main:
            main:
              - path: /app/storage/app/public
                readOnly: false
