---
apiVersion: v1
kind: ConfigMap
metadata:
  name: theitdept-config
  namespace: theitdept-au
data:
  APP_NAME: "theitdept.au"
  APP_ENV: "production"
  APP_DEBUG: "false"
  APP_LOG_LEVEL: "debug"
  APP_LOCALE: "en"
  APP_URL: "https://theitdept.au"
  APP_VERSION: "3.0.1"
  ENABLE_CUSTOM_DOMAINS: "true"
  ENABLE_CONTACT_PAGE: "true"
  BILLING_ENABLED: "true"
  API_INTEGRATED: "true"
  INSTALLED: "true"
  APP_TIMEZONE: "Australia/Sydney"
  DISABLE_UPDATE_AUTH: "false"
  NOTIFICATIONS_ENABLED: "true"
  WORKSPACES_ENABLED: "true"
  NEW_WORKSPACE_FILTER: "true"
  SCOUT_DRIVER: "mysql"
  SCOUT_MYSQL_MODE: "extended"
  SCOUT_PREFIX: "theitdeptau_"

  DB_CONNECTION: "mysql"
  DB_HOST: "theitdept-au-mysql"
  DB_PORT: "3306"
  DB_DATABASE: "theitdept"
  DB_USERNAME: "theitdept"
  DB_PREFIX: ""

  BROADCAST_DRIVER: "log"
  CACHE_DRIVER: "redis"
  SESSION_DRIVER: "database"
  QUEUE_DRIVER: "redis"

  REDIS_HOST: "theitdept-au-redis-master"
  REDIS_DB: "1"
  REDIS_CACHE_DB: "2"
  REDIS_PORT: "6379"

  MAIL_MAILER: smtp
  MAIL_ENCRYPTION: "null"
  MAIL_FROM_ADDRESS: hello@theitdept.au
  MAIL_FROM_NAME: "theitdept.au"

  MAIL_DRIVER: "smtp"
  MAIL_HOST: "postal.theitdept.au"
  MAIL_PORT: "2999"
  MAIL_USERNAME: "the-it-dept/website"

  SANCTUM_STATEFUL_DOMAINS: "theitdept.au"
  SESSION_DOMAIN: "theitdept.au"

  PUSHER_APP_ID: ""
  PUSHER_APP_KEY: ""
  PUSHER_APP_SECRET: ""

  REMOTE_FILE_VISIBILITY: "private"
  USE_PRESIGNED_S3_URLS: "true"
  STATIC_FILE_DELIVERY: ""
  UPLOADS_DISK_DRIVER: "local"
  PUBLIC_DISK_DRIVER: "local"
