---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: theitdept-au
  namespace: theitdept-au
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=http://charts.nicko170.au/
      chart: laravel
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: nicko170-charts
        namespace: flux-system
      interval: 5m

  values:
    image:
      repository: ghcr.io/nicko170/crater
      tag: latest


    imagePullSecrets:
      - name: regcred

    web:
      enabled: true
      count: 1
      command: /cnb/process/web

    cron:
      enabled: false
      command: /cnb/process/schedule
      schedule: "*/1 * * * *"

    worker:
      enabled: true
      count: 1
      command: /cnb/process/worker

    env:
      TZ: "Australia/Sydney"
      PORT: 8080

    envFrom:
      - configMapRef:
          name: theitdept-config
      - secretRef:
          name: theitdept-secrets

    ingress:
      enabled: true
      ingressClassName: "nginx"

      hosts:
        - host: "theitdept.au"
          paths:
            - path: /
              pathType: Prefix

      tls:
        - hosts:
            - "theitdept.au"
          secretName: "theitdept.au"

      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production

    redis:
      enabled: true
      global:
        storageClass: zfs

    mysql:
      enabled: true

      image:
        repository: bitnami/mysql
        tag: 8.0.31-debian-11-r20
        pullPolicy: IfNotPresent

      auth:
        username: theitdept
        database: theitdept
        rootPassword: "${SECRET_LN_DB_PASSWORD}"
        password: "${SECRET_LN_DB_PASSWORD}"

      primary:
        persistence:
          enabled: true
          size: 25Gi
          storageClass: zfs

      secondary:
        replicaCount: 0
