---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-cert-manager
  namespace: flux-system
spec:
  interval: 10m
  path: "./k8s/base/cert-manager/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
