---
apiVersion: v1
kind: Secret
metadata:
    name: ln-secrets
    namespace: ln-au
type: Opaque
stringData:
    APP_KEY: ENC[AES256_GCM,data:5MSeStPBRWgtCh3VVNGYFyBJZGsiaDDhtNxlRMfhq1ljPx11NhEaw0nr2758kQDThTic,iv:8O7+TS7nxQQLCBVPxFA4oIRznVMl6v2iqYiolwITGHY=,tag:XK8WJrKsLlImjqCqYBLI7A==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:eqJOVvVWHxEUFJ09CLY0Uxz8nIto,iv:xz/+zPHrBPJ5NGgNCOMduBGuGWb8+ROdkUKgJkdSYKc=,tag:A4+hqDdnedUq7bqtgllqSg==,type:str]
    REDIS_PASSWORD: ""
    MAIL_PASSWORD: ENC[AES256_GCM,data:ZpGl4P2V/v9ActGWqYqcXTuxy26712+L,iv:slBSrO6iQICEgDLd7qp/hJi9+xp4/+YFg7+6csNKY48=,tag:2Fb1twKP74So1qtMvNsVdA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-12-24T10:46:46Z"
    mac: ENC[AES256_GCM,data:h+wcdxbn/fBKZISrUtqXkdqndlncBuv5xvRn1pHvpxNrm9yQP9C7/DyK+xUs4g/AP/OAiw5LbNSKrgR3i4JDui7BSJ+z3kkufXJkmVqVJySOVs3OLPmh/Gwf2u1e6nSimA23rJ82Gns2qtzK+AwW7DxqDFqQyWZr1KRPQUGhLGA=,iv:9/504aQYl0ustSTGMor9Fsq19KBETBufElYUOXWQUfM=,tag:d4o9vxxAfSoHKMuB4GpCSA==,type:str]
    pgp:
        - created_at: "2022-12-24T10:46:44Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA+n1IkN6s1SvAQ/+Lujy03hKtHKiNCBS6oJdOThMSdbSrNHjf4h1OPrvSTQB
            JcmrTIsKTi53VvMeQWPFYHmax6rIZb3CQR18BTSMkXouLP7e7G1hWkma7exMDnGm
            REIcmMfU4gyxShCR/BJ6nlqa/5mlJ4t1fiYyp9GbxOO1ENJhNVyDMXRtyVNOfpWI
            zjHLaTuPY10LLv1gwVLsg6fcIQbPvpgVdDwiemzDyqtGtykcru4pwCOpouv7Hn6m
            cEI1G8a7atkuv8MHtBu9+VYSVydNXhbii8FUmINksfdAZk6OTEDxokY8Jx3JS7PK
            fBZvqI/ngncKK/RwEGhOdCU1PC5eC5WVNxicItyiQURpv17JElptYaze78OX/xmK
            CMvyM+Crtd/JjAcd5udSkEgx0Vw0THJ6eVd7MoQAbSN0f76FAjzbBniB+RbpIUSj
            6sM+KIOrxZgjB9n98uc3elZF6+unsnZIcfvUuDIZcpqjRLW3vv3efilT58pmnwRi
            7h5UUDMBnkGR4Xil/JMc0iSJxlB+Hqt1Zl2h19In4hrZx/rJx4DFwy9v2rtBz1Bg
            kdlUpp02dGH37gKhLCYBNZyjhA6UDJvmI1CUmYPM1HfJzcAioVeF3laWMVcppHDx
            OqLpW1WssTIKCebOuJ4EKE4eFCfc/RLXuRLeehHjOJQBm7Mk7chHJ8aml1zquUXU
            aAEJAhC7Bsc8pPOvHJlmGc9ZkncK/lcGFZvg5Vovp3Qdpn2UFPugSdKis1AyYMAC
            AsAhacmnxukdCwV3B0Z3651HlJVm0ilSv5PtROpW65LHyn8HdFJ78kUiXRgK2VFr
            /dvP/nxbviU+
            =KlcQ
            -----END PGP MESSAGE-----
          fp: 1DBC92C5001CDAE01E6A730CFC82278B6F8AA349
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
