apiVersion: v1
kind: Secret
metadata:
    name: ln-secrets
    namespace: ln-au
type: Opaque
stringData:
    APP_KEY: ENC[AES256_GCM,data:Os6UgvtqHE+TzGuBtQe+SqPX62e8pbm8eNUtXTm4mlBPZrrJ+eCJ4jk+5mJUFvKOF8eD,iv:zVKG/Lmv0pBSkTcFtndWiYMBM63BbWXiNC+oIR0aWOw=,tag:maEKVEeXvqgc0znmdOb1LA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:ZSCawNsiDMjP2xmE/WWeBFW3YEQi,iv:kDgroxTx7rMH6NbK8blH+UcoJwgPs3XspLxCG9ke640=,tag:1PY0RvmxzNkfJNXzjM0DiA==,type:str]
    REDIS_PASSWORD: ""
    MAIL_PASSWORD: ENC[AES256_GCM,data:Fckxp43CZyvqZ0zBa7OKE2XBFSB4V3CK,iv:odl/m0D+vAijwCbXW+fPOmgaHBAOjFXal+k63Z3lKc8=,tag:qrq9qppE9Y/utYqzM7iS4Q==,type:str]
    STRIPE_KEY: ENC[AES256_GCM,data:GP8crpB3Y0UitrLykPlqAY64DIDDHmRvG6K/3EkdgEsMAFa+IEuGiwbhjqC/hBhD2CaOtABXI8qE7sFnao/HVjHa8IDbZoX77ELZO66gZ5tl4YWgs1n9j7Lhg/SRzrvZkhNj9HNxw8aQPeg=,iv:4NrXhueYUJY15WTSSBHj9fESTF/a5tsUQL//b05mbcI=,tag:BP25jPKFRjnS3LQI350UlA==,type:str]
    STRIPE_SECRET: ENC[AES256_GCM,data:ZkJi8pzQDPY+AxMMao3Yp159Mx7gVaQ1riSYxf0AOiI/9g3VdeOQ0rMIdoMhBmKyB/fl3b+ntj+wkzwzLeN68cyGOcq0C38iBTKIQDwRP4AFUJDJDQ/qOv/l7rcqo/g+1DZbD5rkrv2UR7c=,iv:bjhOBtdjul+DVV1tdzUnvSW88synITdqIMG6o49bcKQ=,tag:+cuH5xsvsr8yQKB6BMLPmQ==,type:str]
    STRIPE_WEBHOOK_SECRET: ENC[AES256_GCM,data:17z0fG1lPpx3I0fq4Dhsvo8B47el3aIXZj+BA5LJLSSUiHKAqBw=,iv:z7FyroLKGIS2zrBwC0EuZO2T76Vjwvp4SAv80E2391w=,tag:VkuXkxREy1o7AORUE+9grg==,type:str]
    PAYPAL_CLIENT_ID: ENC[AES256_GCM,data:hzCEK83uRf0rMNpUg3O2ypvK3SS69feLlKl8vzdghKfohP8kYI+R9buNTskrjasuHNOPgN5z4nE8C5X3vHJE7GBGWmrPkt65MzXWZm7Z0V8=,iv:hcG5hlTvTabzXX5AkciLsSgQW6waPYwYtmEZV7jzL9U=,tag:e0aW05Ws8cywKcKQxtslng==,type:str]
    PAYPAL_SECRET: ENC[AES256_GCM,data:jyiM2RU3eZtzoPk2NGicLECJh+M+5dv8rc83v05UF3qql7JBuZfpEFHNp29KfPqne+h4cxc3cKWB5l0JvvAqW2aKHMidb3L2s7jRCd/PZsc=,iv:peFRV0yyQbMTgdOuM6OTmQaIJjrkW/L+9nHxHn1CpEs=,tag:Js7f5hOsJQVLNWt46X1myw==,type:str]
    PAYPAL_WEBHOOK_ID: ENC[AES256_GCM,data:WWApWXDntHskWT8UNyRrlbE=,iv:eehXxYxo7jC1BN/sCnG64WqNXbUfdb38kGSL+GGB2Ks=,tag:D5JFBF2L2/b8kOEFXE6v4Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-01-06T04:17:37Z"
    mac: ENC[AES256_GCM,data:y7BVbzonYz/6mOjqqqzjZs4jXOZsTEU0bPE5B3ZPS8plb1PaRxmMXQktB5vcNchlzI4nZhlruei+SlYBoU7FVgI14ODoaD8JUbH/qZNaeb2pqDnyp5vC8hBgsyBbFFo0YQ0dPsd5xcMDFKhFIZECBt6igXj+X6W22ba9P+gOFMk=,iv:eT8pGRIVyDU0aNeigiJCyx5hRioz+psw5hnN09kxoww=,tag:riA403stthZKFsQVppqznw==,type:str]
    pgp:
        - created_at: "2023-01-06T04:17:35Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA+n1IkN6s1SvARAAl3NQotJRgmNC5yDNlFlTQf+eGOv+e8ZTyBFgjZEeh8ZE
            YyBsFw2kNX92BHyGXYQ9Ha9DAFcRGTXu4ce/loWmjTcMaCeggA3V4J6n36pQXZdy
            8cLaAXRejmRg2gH741Xkd7vqzSVMXXSSiGNCu8MTJYVxI07wYFP15djZv+EPpmU2
            38pwxN4Kn1M3BRXpOSkFRJKiwww1VMLUmKbdGPQqwtP3zQtPAmQjVCBciUZobpz7
            K8/NWVfdjKnewk1ra+Y28G+eES9ldhoaud53oBY3ECgi/oI1UWg47y1Q8euYA1qM
            18sxa0vgMK5uCpR7zCk1SUYhnLRQVCOai2lCmaHo3P9K0MgS+/2jCpjgR33Bn7lV
            aog1OQ9HiAjAp082iKb2i7EG00TC6j9HNhmnl8pWI/cn9qlJOtNZClBPM35Xpa9m
            5jgDZEr94Badw7ZCI7pdBnjFCjTikkWHbstCBrW3XCGXK6qX2TNjp3Y0prjrFUHo
            /NIGp6qZ8sDCKqixttOMDaK3/JlDsitlRAk1WmDFvDz4+4k8azyMS2gLApixWMI+
            Cx0jSqTGLJQd+Dc5YFK34YCD6r4QPBqEhtJ9hpHTsJ0Tm2U1c7HqTlx75TWaPhgq
            8S3d9FAqW9m57yAgbgJRv/vYWA3GHJN2COtrUyHJQVq/nJsMndCYCrJUjzejs7XU
            ZgEJAhDXuD28K916mTK6dYSAVLHH0eZishdO/IhrpVPly1zqqVDPlLE6kxlch8Xm
            B2b/iqbNkM26xhmueKtCkaZSQQxlhzojfbAjkNOBl+ANPFNHGuFt80F3QudkEZCr
            MVmPslJQ6Q==
            =XHwx
            -----END PGP MESSAGE-----
          fp: 1DBC92C5001CDAE01E6A730CFC82278B6F8AA349
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
