---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra-rook-ceph-cluster
  namespace: flux-system
spec:
  path: ./k8s/base/rook/rook-ceph-cluster/
  prune: true
  dependsOn:
    - name: infra-rook-ceph
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 30m
  retryInterval: 1m
  timeout: 3m
