---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: portal-app-radius
  namespace: portal

spec:
  releaseName: portal-app-radius
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system

  values:
    defaultPodOptions:
      imagePullSecrets:
        - name: ghcr-secret

    controllers:
      main:
        strategy: RollingUpdate
        containers:
          main:
            image:
              repository: ghcr.io/the-it-dept/node-isp
              tag: radius-v0.2.3
              pullPolicy: IfNotPresent

            envFrom:
              - secretRef:
                  name: portal-secrets
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              initialDelaySeconds: 30
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
              httpGet:
                path: /live
                port: 8080

            readiness:
              enabled: true
              custom: true
              spec:
                initialDelaySeconds: 30
                periodSeconds: 10
                timeoutSeconds: 1
                failureThreshold: 3
                httpGet:
                  path: /ready
                  port: 8080

    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Local
        ports:
          http:
            port: 8080
          acct:
            port: 1812
            protocol: UDP
          auth:
            port: 1813
            protocol: UDP
