---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-media
  namespace: media
spec:
  releaseName: kube-media
  chart:
    spec:
      chart: kube-media
      version: 0.3.1
      sourceRef:
        kind: HelmRepository
        name: kube-media-charts
        namespace: flux-system
  interval: 5m
  values:
    general:
      ingress_host: media-admin.theitdept.au
      overseerr_ingress_host: requests.theitdept.au
      plex_ingress_host: plex.theitdept.au

      storage:
        customVolume: true
        volumes:
          nfs:
            server: 172.24.0.1
            path: /rust-store/media
            readOnly: false

        config: # split out from storage to allow for different storage class, such as SSD.
          pvcName: kube-media-config-pvc
          customVolume: false  # set to true if not using a PVC (must provide volume below)
          volumes: { }
          size: 50Gi
          pvcStorageClass: 'local-path'

    plex:
      container:
        nodeSelector:
          externallb: "yes"

      image:
        repository: plexinc/pms-docker
        pullPolicy: IfNotPresent
      enabled: true

      config:
        ALLOWED_NETWORKS: "10.42.0.0/16"

      ingress:
        tls:
          enabled: true
          secretName: theitdept-cloudflare
        annotations: &baseAnnotations
          kubernetes.io/ingress.class: "nginx"
          cert-manager.io/cluster-issuer: "letsencrypt-production"

      extraVolumes: 
        - name: vol-media-01
          nfs:
            server: 100.69.2.2
            path: /vol_media_01
            readOnly: true

      extraMounts: 
        - name: vol-media-01
          mountPath: /mnt/vol_media_01
          readOnly: true

      kubePlex:
        enabled: false
        mounts: /transcode,/media # ,/mnt/vol_media_01

    overseerr:
      enabled: true
      ingress:
        tls:
          enabled: true
          secretName: theitdept-cloudflare
        annotations: *baseAnnotations

    service: &service
      enabled: true
      ingress:
        annotations: *baseAnnotations
        tls:
          enabled: true
          secretName: theitdept-cloudflare

    sonarr: *service
    lidarr: *service
    radarr: *service
    prowlarr: *service
    sabnzbd: *service
    # transmission: *service
    tautulli: *service
