---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-portal-postgres
  namespace: flux-system
spec:
  interval: 10m
  path: ./k8s/staging.syd.node.net.au/apps/portal/postgres
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
