apiVersion: v1
kind: Secret
metadata:
    name: portal-secrets
    namespace: portal
stringData:
    APP_NAME: ENC[AES256_GCM,data:eLoq1IF+KwyM9RCCLWAdn6cH,iv:/gEh0C8H1G+v4VWvqEUkmzCAIuU4ZgZIH2wXlO4h08Q=,tag:d9JMBJJdJOzXqPj2TlxRVw==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:8k3M1KdbGY22xU3ViwxO6lOEmOWN7Jhv6+u9M0Pii+aa+D0YYX3c9FuJQjCr6Sk6/6aB9KXIObLBM//y0jSKHbAsZ0jfiYbwRAZ2hHxKzrApbq/hNCZ31KeCnqzyDw==,iv:o5/miqKg6WZTnwVVlna7mQma7oY9OGXvMIe49xgKAXs=,tag:BIUeBm9iRBjkYyIokfpEcg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:yUwZCc6AFJf1YRY+7E4YRS2R+NRj0cT6v/rDHpfAlcp+JCHOT7qsgQIpYemy6Yy5fiCdjCoLYe2ttPW3dgcZrsWlb1vMRmb4mSYyaj01/CAkecyxwve3hoXih4zJGA==,iv:mD7DUNpqtQCObKnoluZ+nMHQ/1o2ZlLHemWMD2bC4Qg=,tag:vuwT2O6k+urUU8NBXQZpFA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mfp32e7fyypeyfcp6x2zhh4hkym9ra6fyv3g4p7n3klrepefx3ns7uq276
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuVTUycDE4VnhUZktJY1hL
            UXM1MUZRb0hjVTF3czFtWlIyZHQ1OUh0cENnCnRNcVhXdThtL2t4cWZrdk1Ba25q
            QWFlMmpMcGZSZDVGSTZMMEFZbUdJV0EKLS0tIHNNL2MxbC9lNWwxby9SN05ZSXBm
            c3ZUdjFwRWppQWs2U3V2WEJtcWVVRDQKNjprNXfOkrLpBM2+9/7pgDSk6I2PZVyY
            bbNCgFbCfndVuIGfo2pWZk+xCAgtrXQtTxA0xf3eIp/SK0Y/NMl+Tw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-03T12:22:14Z"
    mac: ENC[AES256_GCM,data:vNLM7+PxhSgEdK4Bn85/m+4HpGBf1IoW5QQ8AKGOhJnXiCA4zGwyhXhhHZXQD5WdNStCheyGs+A8Gjz22LkVhS9ta1lG2+Kje7k1lb5IBwbx0fpFtz+Erb2Q57CL3Hkkm1yEOFF516VflRCtaM2C4xc2a3jzK65AHmvrpwhIayg=,iv:kw8w5V9Zcl28Y81+u/kMhyGljBIRyZTT6DtujRFHeSI=,tag:Wosd4f5a0JAZdgiWHww3oA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
