---
name: "Lint"

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          fetch-depth: 0

      - name: Generate Token
        uses: tibdex/github-app-token@021a2405c7f990db57f5eae5397423dcc554159c # renovate: tag=v1.7.0
        id: generate-token
        with:
          app_id: "${{ secrets.BOT_APP_ID }}"
          private_key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: MegaLinter
        uses: oxsecurity/megalinter@8fd433c675d27ceca5a61ace53177c1bbfbf7f49 # v6.18.0
        env:
          GITHUB_TOKEN: "${{ steps.generate-token.outputs.token }}"
          PRINT_ALPACA: false
          VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'workflow_dispatch' }}
          ENABLE_LINTERS: |-
            ${{
              join(
                fromJSON('
                  [
                    "ACTION_ACTIONLINT",
                    "ANSIBLE_ANSIBLE_LINT",
                    "REPOSITORY_GIT_DIFF",
                    "REPOSITORY_SECRETLINT",
                    "TERRAFORM_TERRAFORM_FMT",
                  ]
                '),
                ','
              )
            }}
          ANSIBLE_DIRECTORY: ansible
